"""
SentinelForge Agent 1: Frame Architect
Generates CUDA kernels for image calibration: dark subtraction, flat fielding,
and sigma-clipped background estimation on GPU.
"""
import sys, os, json, time
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from pathlib import Path
from config import PIPELINE_SPEC, SENSOR_SPECS, OUTPUT_DIR
from db import log_action, register_artifact, update_task_state

AGENT_ID = 1
OUTPUT_PATH = OUTPUT_DIR / "builds" / "src"


def execute(task):
    """Generate calibration CUDA source files."""
    title = task.get("title", "").lower()
    
    if "calibrat" in title or "dark" in title or "flat" in title:
        return generate_calibration_kernel(task)
    elif "background" in title:
        return generate_background_kernel(task)
    else:
        return generate_calibration_kernel(task) and generate_background_kernel(task)


def generate_calibration_kernel(task):
    """Generate calibration.cu — dark subtraction + flat field division."""
    OUTPUT_PATH.mkdir(parents=True, exist_ok=True)
    filepath = OUTPUT_PATH / "calibration.cu"
    
    spec = SENSOR_SPECS["varda"]
    w, h = spec["ccd_pixels"]
    
    code = f'''/**
 * calibration.cu — SentinelForge Edge Pipeline
 * GPU-accelerated dark subtraction and flat field correction.
 * Generated by Agent 1 (Frame Architect)
 * 
 * Target: {w}x{h} @ {spec["bit_depth"]}-bit CCD frames
 * GPU: NVIDIA Jetson AGX Orin (CUDA 12.2)
 */

#include <cuda_runtime.h>
#include <cstdint>
#include <cstdio>
#include <cmath>

// ─── Error Checking Macro ──────────────────────────────────────
#define CUDA_CHECK(call) do {{ \\
    cudaError_t err = call; \\
    if (err != cudaSuccess) {{ \\
        fprintf(stderr, "CUDA error at %s:%d: %s\\n", \\
                __FILE__, __LINE__, cudaGetErrorString(err)); \\
        return false; \\
    }} \\
}} while(0)

// ─── Constants ─────────────────────────────────────────────────
constexpr int FRAME_WIDTH  = {w};
constexpr int FRAME_HEIGHT = {h};
constexpr int FRAME_PIXELS = FRAME_WIDTH * FRAME_HEIGHT;
constexpr int BLOCK_DIM    = 16;  // 16x16 = 256 threads per block

/**
 * Kernel: Dark Subtraction
 * Removes thermal noise pattern captured with shutter closed.
 * frame[i] = max(0, frame[i] - dark[i])
 */
__global__ void dark_subtract_kernel(
    float* __restrict__ frame,
    const float* __restrict__ dark,
    int width, int height
) {{
    int x = blockIdx.x * blockDim.x + threadIdx.x;
    int y = blockIdx.y * blockDim.y + threadIdx.y;
    if (x >= width || y >= height) return;
    
    int idx = y * width + x;
    frame[idx] = fmaxf(0.0f, frame[idx] - dark[idx]);
}}

/**
 * Kernel: Flat Field Division
 * Normalizes pixel-to-pixel sensitivity variations.
 * frame[i] = frame[i] / flat[i]
 * flat is pre-normalized to median=1.0
 */
__global__ void flat_divide_kernel(
    float* __restrict__ frame,
    const float* __restrict__ flat,
    int width, int height
) {{
    int x = blockIdx.x * blockDim.x + threadIdx.x;
    int y = blockIdx.y * blockDim.y + threadIdx.y;
    if (x >= width || y >= height) return;
    
    int idx = y * width + x;
    float f = flat[idx];
    // Guard against dead pixels (flat=0)
    frame[idx] = (f > 0.001f) ? frame[idx] / f : 0.0f;
}}

/**
 * Kernel: Convert uint16 raw to float32
 * CCD outputs 16-bit unsigned; pipeline works in float32.
 */
__global__ void uint16_to_float_kernel(
    const uint16_t* __restrict__ raw,
    float* __restrict__ out,
    int width, int height
) {{
    int x = blockIdx.x * blockDim.x + threadIdx.x;
    int y = blockIdx.y * blockDim.y + threadIdx.y;
    if (x >= width || y >= height) return;
    
    int idx = y * width + x;
    out[idx] = static_cast<float>(raw[idx]);
}}

// ─── Host Interface ────────────────────────────────────────────

/**
 * CalibrateFrame: Full calibration pipeline on GPU.
 * 
 * Steps:
 *   1. Convert uint16 raw → float32
 *   2. Subtract master dark frame
 *   3. Divide by master flat field
 * 
 * All buffers must be pre-allocated on GPU.
 * Returns false on CUDA error.
 */
bool CalibrateFrame(
    const uint16_t* d_raw,     // GPU: raw 16-bit frame
    float* d_frame,            // GPU: output float32 frame
    const float* d_dark,       // GPU: master dark (float32)
    const float* d_flat,       // GPU: master flat (float32, normalized)
    int width, int height,
    cudaStream_t stream = 0
) {{
    dim3 block(BLOCK_DIM, BLOCK_DIM);
    dim3 grid((width + BLOCK_DIM - 1) / BLOCK_DIM,
              (height + BLOCK_DIM - 1) / BLOCK_DIM);
    
    // Step 1: uint16 → float32
    uint16_to_float_kernel<<<grid, block, 0, stream>>>(d_raw, d_frame, width, height);
    CUDA_CHECK(cudaGetLastError());
    
    // Step 2: Subtract dark
    dark_subtract_kernel<<<grid, block, 0, stream>>>(d_frame, d_dark, width, height);
    CUDA_CHECK(cudaGetLastError());
    
    // Step 3: Divide by flat
    flat_divide_kernel<<<grid, block, 0, stream>>>(d_frame, d_flat, width, height);
    CUDA_CHECK(cudaGetLastError());
    
    return true;
}}

// ─── Master Frame Generation ───────────────────────────────────

/**
 * Kernel: Accumulate frames for master dark/flat creation.
 * Computes running sum for later averaging.
 */
__global__ void accumulate_kernel(
    float* __restrict__ accumulator,
    const float* __restrict__ frame,
    int width, int height
) {{
    int x = blockIdx.x * blockDim.x + threadIdx.x;
    int y = blockIdx.y * blockDim.y + threadIdx.y;
    if (x >= width || y >= height) return;
    
    int idx = y * width + x;
    accumulator[idx] += frame[idx];
}}

/**
 * Kernel: Divide accumulator by N to get average.
 */
__global__ void average_kernel(
    float* __restrict__ accumulator,
    int n_frames,
    int width, int height
) {{
    int x = blockIdx.x * blockDim.x + threadIdx.x;
    int y = blockIdx.y * blockDim.y + threadIdx.y;
    if (x >= width || y >= height) return;
    
    int idx = y * width + x;
    accumulator[idx] /= static_cast<float>(n_frames);
}}

/**
 * Kernel: Normalize flat field to median=1.0
 */
__global__ void normalize_flat_kernel(
    float* __restrict__ flat,
    float median_value,
    int width, int height
) {{
    int x = blockIdx.x * blockDim.x + threadIdx.x;
    int y = blockIdx.y * blockDim.y + threadIdx.y;
    if (x >= width || y >= height) return;
    
    int idx = y * width + x;
    flat[idx] = (median_value > 0.0f) ? flat[idx] / median_value : 1.0f;
}}

// ─── GPU Memory Manager ───────────────────────────────────────

struct CalibrationBuffers {{
    float* d_frame;
    float* d_dark;
    float* d_flat;
    uint16_t* d_raw;
    int width;
    int height;
    
    bool allocate(int w, int h) {{
        width = w;
        height = h;
        size_t float_bytes = w * h * sizeof(float);
        size_t raw_bytes = w * h * sizeof(uint16_t);
        
        CUDA_CHECK(cudaMalloc(&d_frame, float_bytes));
        CUDA_CHECK(cudaMalloc(&d_dark, float_bytes));
        CUDA_CHECK(cudaMalloc(&d_flat, float_bytes));
        CUDA_CHECK(cudaMalloc(&d_raw, raw_bytes));
        
        printf("[CalibrationBuffers] Allocated %.1f MB GPU memory\\n",
               (float_bytes * 3 + raw_bytes) / (1024.0f * 1024.0f));
        return true;
    }}
    
    void release() {{
        cudaFree(d_frame);
        cudaFree(d_dark);
        cudaFree(d_flat);
        cudaFree(d_raw);
        d_frame = d_dark = d_flat = nullptr;
        d_raw = nullptr;
    }}
}};
'''

    filepath.write_text(code, encoding="utf-8")
    lines = len(code.splitlines())
    
    register_artifact(task["id"], AGENT_ID, str(filepath), "cuda", lines, "1.0")
    log_action(AGENT_ID, "GENERATE_CODE", task["id"],
               details={"file": str(filepath), "lines": lines},
               files_modified=[str(filepath)], status="SUCCESS")
    
    print(f"           -> Generated calibration.cu ({lines} lines)")
    return True


def generate_background_kernel(task):
    """Generate background.cu — sigma-clipped tiled sky background estimation."""
    OUTPUT_PATH.mkdir(parents=True, exist_ok=True)
    filepath = OUTPUT_PATH / "background.cu"
    
    spec = PIPELINE_SPEC
    tile = spec["background_tile_size_px"]
    sigma = spec["sigma_clip_threshold"]
    iters = spec["sigma_clip_iterations"]
    
    code = f'''/**
 * background.cu — SentinelForge Edge Pipeline
 * GPU-accelerated sky background estimation and subtraction.
 * Uses sigma-clipped median on {tile}x{tile} tiles.
 * Generated by Agent 1 (Frame Architect)
 */

#include <cuda_runtime.h>
#include <cstdio>
#include <cmath>
#include <algorithm>

constexpr int TILE_SIZE    = {tile};
constexpr int TILE_PIXELS  = TILE_SIZE * TILE_SIZE;  // {tile*tile}
constexpr float SIGMA_CLIP = {sigma}f;
constexpr int CLIP_ITERS   = {iters};

/**
 * Device function: Insertion sort for small arrays (in shared memory).
 * Used within each tile to compute median.
 */
__device__ void insertion_sort(float* arr, int n) {{
    for (int i = 1; i < n; i++) {{
        float key = arr[i];
        int j = i - 1;
        while (j >= 0 && arr[j] > key) {{
            arr[j + 1] = arr[j];
            j--;
        }}
        arr[j + 1] = key;
    }}
}}

/**
 * Kernel: Compute sigma-clipped median for each tile.
 * Each block handles one {tile}x{tile} tile.
 * Output: one background value per tile.
 */
__global__ void tile_median_kernel(
    const float* __restrict__ frame,
    float* __restrict__ bg_map,
    int frame_width, int frame_height,
    int tiles_x, int tiles_y
) {{
    int tile_x = blockIdx.x;
    int tile_y = blockIdx.y;
    if (tile_x >= tiles_x || tile_y >= tiles_y) return;
    
    // Thread index within tile
    int tid = threadIdx.x;
    
    // Shared memory for tile pixels
    __shared__ float tile_data[TILE_PIXELS];
    __shared__ float valid_data[TILE_PIXELS];
    __shared__ int valid_count;
    
    // Load tile pixels into shared memory
    int px = tile_x * TILE_SIZE + (tid % TILE_SIZE);
    int py = tile_y * TILE_SIZE + (tid / TILE_SIZE);
    
    if (tid < TILE_PIXELS && px < frame_width && py < frame_height) {{
        tile_data[tid] = frame[py * frame_width + px];
    }} else if (tid < TILE_PIXELS) {{
        tile_data[tid] = 0.0f;
    }}
    __syncthreads();
    
    // Thread 0 performs sigma-clipped median
    if (tid == 0) {{
        // Copy to working array
        int n = TILE_PIXELS;
        for (int i = 0; i < n; i++) valid_data[i] = tile_data[i];
        
        // Sigma clipping iterations
        for (int iter = 0; iter < CLIP_ITERS; iter++) {{
            // Sort
            insertion_sort(valid_data, n);
            
            // Median
            float med = valid_data[n / 2];
            
            // MAD (Median Absolute Deviation)
            float deviations[TILE_PIXELS];
            for (int i = 0; i < n; i++)
                deviations[i] = fabsf(valid_data[i] - med);
            insertion_sort(deviations, n);
            float mad = 1.4826f * deviations[n / 2];
            
            // Reject outliers
            if (mad < 0.001f) break;  // All values identical
            int new_n = 0;
            for (int i = 0; i < n; i++) {{
                if (fabsf(valid_data[i] - med) < SIGMA_CLIP * mad) {{
                    valid_data[new_n++] = valid_data[i];
                }}
            }}
            if (new_n < 4) break;  // Too few pixels left
            n = new_n;
        }}
        
        // Final median
        insertion_sort(valid_data, n);
        bg_map[tile_y * tiles_x + tile_x] = valid_data[n / 2];
    }}
}}

/**
 * Kernel: Bilinear upsample background map to full frame resolution.
 * Smooth interpolation avoids tiling artifacts.
 */
__global__ void upsample_background_kernel(
    const float* __restrict__ bg_map,
    float* __restrict__ bg_full,
    int frame_width, int frame_height,
    int tiles_x, int tiles_y
) {{
    int x = blockIdx.x * blockDim.x + threadIdx.x;
    int y = blockIdx.y * blockDim.y + threadIdx.y;
    if (x >= frame_width || y >= frame_height) return;
    
    // Map pixel to tile coordinates (continuous)
    float tx = (float)x / TILE_SIZE - 0.5f;
    float ty = (float)y / TILE_SIZE - 0.5f;
    
    // Bilinear interpolation
    int tx0 = max(0, (int)floorf(tx));
    int ty0 = max(0, (int)floorf(ty));
    int tx1 = min(tiles_x - 1, tx0 + 1);
    int ty1 = min(tiles_y - 1, ty0 + 1);
    
    float fx = tx - floorf(tx);
    float fy = ty - floorf(ty);
    
    float v00 = bg_map[ty0 * tiles_x + tx0];
    float v10 = bg_map[ty0 * tiles_x + tx1];
    float v01 = bg_map[ty1 * tiles_x + tx0];
    float v11 = bg_map[ty1 * tiles_x + tx1];
    
    float result = v00 * (1-fx) * (1-fy) + v10 * fx * (1-fy)
                 + v01 * (1-fx) * fy     + v11 * fx * fy;
    
    bg_full[y * frame_width + x] = result;
}}

/**
 * Kernel: Subtract background from science frame.
 */
__global__ void subtract_background_kernel(
    float* __restrict__ frame,
    const float* __restrict__ background,
    int width, int height
) {{
    int x = blockIdx.x * blockDim.x + threadIdx.x;
    int y = blockIdx.y * blockDim.y + threadIdx.y;
    if (x >= width || y >= height) return;
    
    int idx = y * width + x;
    frame[idx] = fmaxf(0.0f, frame[idx] - background[idx]);
}}

// ─── Host Interface ────────────────────────────────────────────

struct BackgroundBuffers {{
    float* d_bg_map;
    float* d_bg_full;
    int tiles_x, tiles_y;
    
    bool allocate(int frame_width, int frame_height) {{
        tiles_x = frame_width / TILE_SIZE;
        tiles_y = frame_height / TILE_SIZE;
        
        cudaMalloc(&d_bg_map, tiles_x * tiles_y * sizeof(float));
        cudaMalloc(&d_bg_full, frame_width * frame_height * sizeof(float));
        return true;
    }}
    
    void release() {{
        cudaFree(d_bg_map);
        cudaFree(d_bg_full);
    }}
}};

/**
 * SubtractBackground: Full background estimation and subtraction.
 */
bool SubtractBackground(
    float* d_frame,
    BackgroundBuffers& bufs,
    int width, int height,
    cudaStream_t stream = 0
) {{
    // Step 1: Compute tiled sigma-clipped medians
    dim3 tile_grid(bufs.tiles_x, bufs.tiles_y);
    dim3 tile_block(TILE_PIXELS);  // One block per tile
    tile_median_kernel<<<tile_grid, tile_block, 0, stream>>>(
        d_frame, bufs.d_bg_map, width, height, bufs.tiles_x, bufs.tiles_y
    );
    
    // Step 2: Upsample to full resolution
    dim3 block(16, 16);
    dim3 grid((width + 15) / 16, (height + 15) / 16);
    upsample_background_kernel<<<grid, block, 0, stream>>>(
        bufs.d_bg_map, bufs.d_bg_full, width, height, bufs.tiles_x, bufs.tiles_y
    );
    
    // Step 3: Subtract
    subtract_background_kernel<<<grid, block, 0, stream>>>(
        d_frame, bufs.d_bg_full, width, height
    );
    
    return (cudaGetLastError() == cudaSuccess);
}}
'''

    filepath.write_text(code, encoding="utf-8")
    lines = len(code.splitlines())
    
    register_artifact(task["id"], AGENT_ID, str(filepath), "cuda", lines, "1.0")
    log_action(AGENT_ID, "GENERATE_CODE", task["id"],
               details={"file": str(filepath), "lines": lines},
               files_modified=[str(filepath)], status="SUCCESS")
    
    print(f"           -> Generated background.cu ({lines} lines)")
    return True
