"""
SentinelForge Agent 4: Hardware Interface
Generates C++ drivers for CCD camera capture and telescope mount control.
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from pathlib import Path
from config import SENSOR_SPECS, OUTPUT_DIR
from db import log_action, register_artifact

AGENT_ID = 4
OUTPUT_PATH = OUTPUT_DIR / "builds" / "src"


def execute(task):
    title = task.get("title", "").lower()
    if "camera" in title or "ccd" in title:
        return generate_camera_driver(task)
    elif "mount" in title or "telescope" in title:
        return generate_mount_control(task)
    else:
        return generate_camera_driver(task) and generate_mount_control(task)


def generate_camera_driver(task):
    OUTPUT_PATH.mkdir(parents=True, exist_ok=True)
    filepath = OUTPUT_PATH / "camera_driver.cpp"
    spec = SENSOR_SPECS["varda"]
    w, h = spec["ccd_pixels"]

    code = f'''/**
 * camera_driver.cpp - SentinelForge Edge Pipeline
 * CCD camera capture with thread-safe frame buffer.
 * Target: {w}x{h} @ {spec["bit_depth"]}-bit, {spec["interface"]} interface
 * Generated by Agent 4 (Hardware Interface)
 */

#include <cstdint>
#include <cstdio>
#include <cstring>
#include <queue>
#include <mutex>
#include <thread>
#include <atomic>
#include <chrono>
#include <condition_variable>
#include <functional>

constexpr int FRAME_WIDTH  = {w};
constexpr int FRAME_HEIGHT = {h};
constexpr int BIT_DEPTH    = {spec["bit_depth"]};
constexpr size_t FRAME_BYTES = FRAME_WIDTH * FRAME_HEIGHT * sizeof(uint16_t);
constexpr int MAX_BUFFER_FRAMES = 8;  // Ring buffer depth

// ---- Frame Container ------------------------------------------------

struct Frame {{
    uint16_t* data;
    int width, height;
    double exposure_sec;
    double timestamp;       // Unix epoch, microsecond precision
    double ccd_temp_c;
    int frame_number;

    Frame() : data(nullptr), width(0), height(0), exposure_sec(0),
              timestamp(0), ccd_temp_c(0), frame_number(0) {{}}

    bool allocate(int w, int h) {{
        width = w; height = h;
        data = new (std::nothrow) uint16_t[w * h];
        return data != nullptr;
    }}

    void release() {{
        delete[] data;
        data = nullptr;
    }}

    Frame deep_copy() const {{
        Frame f;
        f.allocate(width, height);
        if (f.data && data)
            memcpy(f.data, data, width * height * sizeof(uint16_t));
        f.exposure_sec = exposure_sec;
        f.timestamp = timestamp;
        f.ccd_temp_c = ccd_temp_c;
        f.frame_number = frame_number;
        return f;
    }}
}};

// ---- Thread-Safe Frame Buffer --------------------------------------

class FrameBuffer {{
private:
    std::queue<Frame> queue_;
    std::mutex mtx_;
    std::condition_variable cv_;
    int max_size_;

public:
    explicit FrameBuffer(int max_size = MAX_BUFFER_FRAMES) : max_size_(max_size) {{}}

    void push(Frame&& frame) {{
        std::lock_guard<std::mutex> lock(mtx_);
        if ((int)queue_.size() >= max_size_) {{
            // Drop oldest frame (overrun)
            Frame old = queue_.front();
            old.release();
            queue_.pop();
            fprintf(stderr, "[CameraDriver] WARNING: buffer overrun, dropped frame\\n");
        }}
        queue_.push(std::move(frame));
        cv_.notify_one();
    }}

    bool pop(Frame& frame, int timeout_ms = 5000) {{
        std::unique_lock<std::mutex> lock(mtx_);
        if (!cv_.wait_for(lock, std::chrono::milliseconds(timeout_ms),
                          [this]() {{ return !queue_.empty(); }})) {{
            return false;  // Timeout
        }}
        frame = queue_.front();
        queue_.pop();
        return true;
    }}

    int size() {{
        std::lock_guard<std::mutex> lock(mtx_);
        return (int)queue_.size();
    }}
}};

// ---- Camera Driver -------------------------------------------------

class CameraDriver {{
private:
    // In production, this would be the vendor SDK handle
    // e.g., Andor SDK, FLI SDK, ZWO ASI SDK
    void* camera_handle_;
    FrameBuffer buffer_;
    std::thread capture_thread_;
    std::atomic<bool> running_{{false}};
    std::atomic<int> frame_count_{{0}};

    double exposure_sec_;
    double cooling_target_c_;
    int binning_x_, binning_y_;

    // Simulated capture for development without hardware
    void simulate_capture(uint16_t* buf, int w, int h) {{
        // Generate noise floor + a few fake stars
        for (int i = 0; i < w * h; i++) {{
            // Poisson noise ~ 100 ADU background + read noise
            buf[i] = (uint16_t)(100 + (rand() % 30));
        }}
        // Inject a few bright "stars"
        for (int s = 0; s < 50; s++) {{
            int sx = rand() % w;
            int sy = rand() % h;
            int brightness = 5000 + (rand() % 10000);
            for (int dy = -2; dy <= 2; dy++)
                for (int dx = -2; dx <= 2; dx++) {{
                    int px = sx + dx, py = sy + dy;
                    if (px >= 0 && px < w && py >= 0 && py < h) {{
                        float dist = sqrtf((float)(dx*dx + dy*dy));
                        int val = (int)(brightness * expf(-dist*dist / 1.5f));
                        buf[py * w + px] = (uint16_t)fmin(65535, buf[py*w+px] + val);
                    }}
                }}
        }}
    }}

    void capture_loop() {{
        printf("[CameraDriver] Capture loop started (%.1fs exposure)\\n", exposure_sec_);
        while (running_) {{
            Frame frame;
            if (!frame.allocate(FRAME_WIDTH, FRAME_HEIGHT)) {{
                fprintf(stderr, "[CameraDriver] ERROR: allocation failed\\n");
                break;
            }}

            // In production: call vendor SDK expose function
            // e.g., Andor: AT_Command(handle, L"AcquisitionStart");
            //        FLI:  FLIExposeFrame(dev);
            simulate_capture(frame.data, FRAME_WIDTH, FRAME_HEIGHT);

            // Simulate exposure time
            std::this_thread::sleep_for(
                std::chrono::milliseconds((int)(exposure_sec_ * 1000))
            );

            frame.width = FRAME_WIDTH;
            frame.height = FRAME_HEIGHT;
            frame.exposure_sec = exposure_sec_;
            frame.frame_number = frame_count_++;
            frame.ccd_temp_c = cooling_target_c_ + 0.1 * (rand() % 10 - 5);

            auto now = std::chrono::system_clock::now();
            frame.timestamp = std::chrono::duration<double>(
                now.time_since_epoch()).count();

            buffer_.push(std::move(frame));
        }}
        printf("[CameraDriver] Capture loop stopped\\n");
    }}

public:
    CameraDriver() : camera_handle_(nullptr), exposure_sec_(1.0),
                     cooling_target_c_(-20.0), binning_x_(1), binning_y_(1) {{}}

    bool init(const char* device_id) {{
        // In production: open vendor SDK connection
        printf("[CameraDriver] Initializing camera: %s\\n", device_id);
        printf("[CameraDriver] Sensor: %dx%d @ %d-bit\\n",
               FRAME_WIDTH, FRAME_HEIGHT, BIT_DEPTH);
        return true;
    }}

    void set_exposure(double seconds) {{ exposure_sec_ = seconds; }}
    void set_cooling(double target_c) {{ cooling_target_c_ = target_c; }}
    void set_binning(int x, int y) {{ binning_x_ = x; binning_y_ = y; }}

    bool start() {{
        if (running_) return false;
        running_ = true;
        capture_thread_ = std::thread(&CameraDriver::capture_loop, this);
        return true;
    }}

    void stop() {{
        running_ = false;
        if (capture_thread_.joinable())
            capture_thread_.join();
    }}

    bool get_frame(Frame& frame, int timeout_ms = 5000) {{
        return buffer_.pop(frame, timeout_ms);
    }}

    int frames_captured() const {{ return frame_count_; }}
    int buffer_depth() const {{ return MAX_BUFFER_FRAMES; }}
    bool is_running() const {{ return running_; }}

    ~CameraDriver() {{ stop(); }}
}};
'''

    filepath.write_text(code, encoding="utf-8")
    lines = len(code.splitlines())
    register_artifact(task["id"], AGENT_ID, str(filepath), "cpp", lines, "1.0")
    log_action(AGENT_ID, "GENERATE_CODE", task["id"],
               details={"file": str(filepath), "lines": lines},
               files_modified=[str(filepath)], status="SUCCESS")
    print(f"           -> Generated camera_driver.cpp ({lines} lines)")
    return True


def generate_mount_control(task):
    OUTPUT_PATH.mkdir(parents=True, exist_ok=True)
    filepath = OUTPUT_PATH / "mount_control.cpp"
    
    code = '''/**
 * mount_control.cpp - SentinelForge Edge Pipeline
 * Telescope mount control via LX200/ASCOM serial protocol.
 * Generated by Agent 4 (Hardware Interface)
 */

#include <cstdio>
#include <cstring>
#include <cmath>
#include <string>
#include <chrono>
#include <thread>

#ifdef _WIN32
  #include <windows.h>
  typedef HANDLE SerialHandle;
#else
  #include <fcntl.h>
  #include <termios.h>
  #include <unistd.h>
  typedef int SerialHandle;
#endif

constexpr double SETTLE_TOLERANCE_ARCSEC = 1.0;
constexpr int    SETTLE_TIMEOUT_SEC      = 30;
constexpr int    BAUD_RATE               = 9600;

// ---- Serial Port Abstraction ---------------------------------------

class SerialPort {
private:
    SerialHandle handle_;
    bool is_open_;

public:
    SerialPort() : is_open_(false) {
#ifdef _WIN32
        handle_ = INVALID_HANDLE_VALUE;
#else
        handle_ = -1;
#endif
    }

    bool open(const char* device, int baud = BAUD_RATE) {
#ifdef _WIN32
        handle_ = CreateFileA(device, GENERIC_READ | GENERIC_WRITE,
                              0, NULL, OPEN_EXISTING, 0, NULL);
        if (handle_ == INVALID_HANDLE_VALUE) return false;
        DCB dcb = {0};
        dcb.DCBlength = sizeof(dcb);
        GetCommState(handle_, &dcb);
        dcb.BaudRate = baud;
        dcb.ByteSize = 8;
        dcb.Parity = NOPARITY;
        dcb.StopBits = ONESTOPBIT;
        SetCommState(handle_, &dcb);
        COMMTIMEOUTS timeouts = {100, 10, 100, 10, 100};
        SetCommTimeouts(handle_, &timeouts);
#else
        handle_ = ::open(device, O_RDWR | O_NOCTTY);
        if (handle_ < 0) return false;
        struct termios tty;
        tcgetattr(handle_, &tty);
        cfsetispeed(&tty, B9600);
        cfsetospeed(&tty, B9600);
        tty.c_cflag = CS8 | CLOCAL | CREAD;
        tty.c_iflag = 0;
        tty.c_oflag = 0;
        tty.c_lflag = 0;
        tty.c_cc[VMIN] = 0;
        tty.c_cc[VTIME] = 1;
        tcsetattr(handle_, TCSANOW, &tty);
#endif
        is_open_ = true;
        printf("[Mount] Serial port %s opened at %d baud\\n", device, baud);
        return true;
    }

    int write_cmd(const char* cmd) {
        int len = (int)strlen(cmd);
#ifdef _WIN32
        DWORD written;
        WriteFile(handle_, cmd, len, &written, NULL);
        return (int)written;
#else
        return (int)::write(handle_, cmd, len);
#endif
    }

    std::string read_until(char terminator, int timeout_ms = 1000) {
        std::string result;
        auto start = std::chrono::steady_clock::now();
        while (true) {
            char c;
#ifdef _WIN32
            DWORD bytesRead;
            ReadFile(handle_, &c, 1, &bytesRead, NULL);
            if (bytesRead == 0) {
#else
            int n = (int)::read(handle_, &c, 1);
            if (n <= 0) {
#endif
                auto elapsed = std::chrono::steady_clock::now() - start;
                if (std::chrono::duration_cast<std::chrono::milliseconds>(elapsed).count() > timeout_ms)
                    break;
                continue;
            }
            if (c == terminator) break;
            result += c;
        }
        return result;
    }

    void close_port() {
        if (!is_open_) return;
#ifdef _WIN32
        CloseHandle(handle_);
#else
        ::close(handle_);
#endif
        is_open_ = false;
    }

    ~SerialPort() { close_port(); }
};

// ---- Coordinate Parsing -------------------------------------------

static double parse_ra(const std::string& s) {
    // Format: "HH:MM:SS" -> decimal hours
    int h = 0, m = 0; double sec = 0;
    sscanf(s.c_str(), "%d:%d:%lf", &h, &m, &sec);
    return h + m / 60.0 + sec / 3600.0;
}

static double parse_dec(const std::string& s) {
    // Format: "+DD*MM:SS" -> decimal degrees
    int d = 0, m = 0; double sec = 0;
    sscanf(s.c_str(), "%d*%d:%lf", &d, &m, &sec);
    double sign = (s[0] == '-') ? -1.0 : 1.0;
    return sign * (abs(d) + m / 60.0 + sec / 3600.0);
}

static double angular_sep(double ra1, double dec1, double ra2, double dec2) {
    // Great-circle distance in degrees
    double ra1r = ra1 * 15.0 * M_PI / 180.0;
    double ra2r = ra2 * 15.0 * M_PI / 180.0;
    double d1r = dec1 * M_PI / 180.0;
    double d2r = dec2 * M_PI / 180.0;
    double dra = ra2r - ra1r;
    double val = sin(d1r)*sin(d2r) + cos(d1r)*cos(d2r)*cos(dra);
    val = fmin(1.0, fmax(-1.0, val));
    return acos(val) * 180.0 / M_PI;
}

// ---- Mount Controller ---------------------------------------------

class TelescopeMount {
private:
    SerialPort port_;
    double ra_current_, dec_current_;
    bool connected_;
    bool simulated_;

public:
    TelescopeMount() : ra_current_(0), dec_current_(0),
                       connected_(false), simulated_(false) {}

    bool connect(const char* device) {
        if (strcmp(device, "SIM") == 0) {
            simulated_ = true;
            connected_ = true;
            printf("[Mount] Simulated mount connected\\n");
            return true;
        }
        connected_ = port_.open(device);
        return connected_;
    }

    bool slew_to(double ra_hours, double dec_deg) {
        if (!connected_) return false;

        printf("[Mount] Slewing to RA=%.4fh Dec=%.4fdeg\\n", ra_hours, dec_deg);

        if (simulated_) {
            // Simulate slew time based on distance
            double dist = angular_sep(ra_current_, dec_current_, ra_hours, dec_deg);
            int slew_ms = (int)(dist * 100);  // ~100ms per degree
            std::this_thread::sleep_for(std::chrono::milliseconds(slew_ms));
            ra_current_ = ra_hours;
            dec_current_ = dec_deg;
            printf("[Mount] Settled at target (simulated)\\n");
            return true;
        }

        // LX200 protocol: set target, then slew
        char cmd[64];

        // Set target RA
        int h = (int)ra_hours;
        int m = (int)((ra_hours - h) * 60);
        double s = (ra_hours - h - m/60.0) * 3600;
        snprintf(cmd, sizeof(cmd), ":Sr%02d:%02d:%04.1f#", h, m, s);
        port_.write_cmd(cmd);

        // Set target Dec
        int dd = (int)dec_deg;
        int dm = abs((int)((dec_deg - dd) * 60));
        double ds = fabs(fmod(dec_deg * 3600, 60.0));
        snprintf(cmd, sizeof(cmd), ":Sd%+03d*%02d:%04.1f#", dd, dm, ds);
        port_.write_cmd(cmd);

        // Slew command
        port_.write_cmd(":MS#");
        std::string resp = port_.read_until('#');
        if (!resp.empty() && resp[0] != '0') {
            fprintf(stderr, "[Mount] Slew rejected: %s\\n", resp.c_str());
            return false;
        }

        // Wait for settle
        auto start = std::chrono::steady_clock::now();
        while (true) {
            port_.write_cmd(":GR#");
            std::string ra_str = port_.read_until('#');
            port_.write_cmd(":GD#");
            std::string dec_str = port_.read_until('#');

            double ra_now = parse_ra(ra_str);
            double dec_now = parse_dec(dec_str);
            double err = angular_sep(ra_now, dec_now, ra_hours, dec_deg);

            if (err < SETTLE_TOLERANCE_ARCSEC / 3600.0) {
                ra_current_ = ra_now;
                dec_current_ = dec_now;
                printf("[Mount] Settled (error: %.2f arcsec)\\n", err * 3600.0);
                return true;
            }

            auto elapsed = std::chrono::steady_clock::now() - start;
            if (std::chrono::duration_cast<std::chrono::seconds>(elapsed).count()
                > SETTLE_TIMEOUT_SEC) {
                fprintf(stderr, "[Mount] Settle timeout (error: %.2f arcsec)\\n",
                        err * 3600.0);
                return false;
            }
            std::this_thread::sleep_for(std::chrono::milliseconds(200));
        }
    }

    void park() {
        printf("[Mount] Parking telescope\\n");
        if (simulated_) { ra_current_ = 0; dec_current_ = 90; return; }
        port_.write_cmd(":hP#");
    }

    double ra() const  { return ra_current_; }
    double dec() const { return dec_current_; }
    bool is_connected() const { return connected_; }
};
'''

    filepath.write_text(code, encoding="utf-8")
    lines = len(code.splitlines())
    register_artifact(task["id"], AGENT_ID, str(filepath), "cpp", lines, "1.0")
    log_action(AGENT_ID, "GENERATE_CODE", task["id"],
               details={"file": str(filepath), "lines": lines},
               files_modified=[str(filepath)], status="SUCCESS")
    print(f"           -> Generated mount_control.cpp ({lines} lines)")
    return True
