"""
SentinelForge Agent 3: Plate Solver
Generates C++ astrometric plate solving and photometry modules.
Queries knowledge base for equations before generating code.
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from pathlib import Path
from config import PIPELINE_SPEC, SENSOR_SPECS, OUTPUT_DIR
from db import log_action, register_artifact
from knowledge import query_equation, query_algorithm

AGENT_ID = 3
OUTPUT_PATH = OUTPUT_DIR / "builds" / "src"


def execute(task):
    title = task.get("title", "").lower()
    if "photom" in title:
        return generate_photometry(task)
    return generate_plate_solver(task)


def generate_plate_solver(task):
    OUTPUT_PATH.mkdir(parents=True, exist_ok=True)
    filepath = OUTPUT_PATH / "plate_solver.cpp"

    # Query knowledge base for algorithm steps
    algo = query_algorithm("plate_solving")
    eq = query_equation("plate_solution")
    psf = query_equation("psf_gaussian")
    max_res = PIPELINE_SPEC["plate_solve_residual_max_arcsec"]

    code = f'''/**
 * plate_solver.cpp - SentinelForge Edge Pipeline
 * Astrometric plate solving: pixel (x,y) -> sky (RA, Dec).
 * Algorithm: {algo.get("name", "Triangle matching")}
 * Max residual: {max_res} arcsec
 * Generated by Agent 3 (Plate Solver)
 */

#include <cstdio>
#include <cmath>
#include <vector>
#include <algorithm>
#include <numeric>

constexpr double MAX_RESIDUAL_ARCSEC = {max_res};
constexpr int    MIN_MATCH_STARS     = {eq.get("min_stars", 6)};
constexpr double TYPICAL_FWHM_PX    = {psf.get("typical_fwhm_px", 2.5)};

// ---- Data Structures -----------------------------------------------

struct PixelSource {{
    double x, y;            // Centroid position (sub-pixel)
    double flux;            // Integrated brightness
    double fwhm;            // Measured FWHM
    double snr;
}};

struct CatalogStar {{
    double ra_deg, dec_deg;
    double magnitude;
    int gaia_id;
}};

struct WCSSolution {{
    double crpix1, crpix2;  // Reference pixel
    double crval1, crval2;  // Reference sky coord (deg)
    double cd[2][2];        // Transformation matrix
    // Higher-order distortion (SIP)
    double a[3][3];         // RA distortion polynomial
    double b[3][3];         // Dec distortion polynomial
    int order;
    double residual_arcsec;
    int n_matched_stars;
    bool valid;

    void pixel_to_sky(double px, double py, double& ra, double& dec) const {{
        double dx = px - crpix1;
        double dy = py - crpix2;
        // Apply SIP distortion if order > 1
        if (order >= 2) {{
            double dx2 = dx, dy2 = dy;
            for (int i = 0; i <= order; i++)
                for (int j = 0; j <= order - i; j++) {{
                    double term = pow(dx, i) * pow(dy, j);
                    dx2 += a[i][j] * term;
                    dy2 += b[i][j] * term;
                }}
            dx = dx2;
            dy = dy2;
        }}
        ra  = crval1 + cd[0][0] * dx + cd[0][1] * dy;
        dec = crval2 + cd[1][0] * dx + cd[1][1] * dy;
    }}
}};

// ---- Source Extraction ---------------------------------------------

struct PSFFitter {{
    /**
     * Fit 2D Gaussian to pixel data around a peak.
     * {psf.get("formula", "I(x,y) = A*exp(...) + B")}
     * Returns sub-pixel centroid (x0, y0).
     */
    static PixelSource fit(const float* frame, int width, int height,
                           int peak_x, int peak_y, int radius = 5) {{
        PixelSource src;
        // Weighted centroid (moment method as initial guess)
        double sum_wx = 0, sum_wy = 0, sum_w = 0;
        double peak_val = frame[peak_y * width + peak_x];

        for (int dy = -radius; dy <= radius; dy++) {{
            for (int dx = -radius; dx <= radius; dx++) {{
                int px = peak_x + dx, py = peak_y + dy;
                if (px < 0 || px >= width || py < 0 || py >= height) continue;
                double val = frame[py * width + px];
                if (val > 0) {{
                    sum_wx += val * px;
                    sum_wy += val * py;
                    sum_w += val;
                }}
            }}
        }}

        src.x = (sum_w > 0) ? sum_wx / sum_w : peak_x;
        src.y = (sum_w > 0) ? sum_wy / sum_w : peak_y;
        src.flux = sum_w;
        src.fwhm = TYPICAL_FWHM_PX;
        src.snr = peak_val / sqrt(100.0 + 10.0*10.0);  // approx
        return src;
    }}
}};

std::vector<PixelSource> extract_sources(const float* frame,
                                          int width, int height,
                                          float threshold_snr = 10.0) {{
    std::vector<PixelSource> sources;
    float noise_est = 15.0f;  // Rough estimate

    for (int y = 5; y < height - 5; y++) {{
        for (int x = 5; x < width - 5; x++) {{
            float val = frame[y * width + x];
            if (val / noise_est < threshold_snr) continue;

            // Local maximum check (3x3)
            bool is_max = true;
            for (int dy = -1; dy <= 1 && is_max; dy++)
                for (int dx = -1; dx <= 1 && is_max; dx++)
                    if ((dx || dy) && frame[(y+dy)*width+(x+dx)] >= val)
                        is_max = false;

            if (is_max) {{
                sources.push_back(PSFFitter::fit(frame, width, height, x, y));
            }}
        }}
    }}

    // Sort by brightness (descending)
    std::sort(sources.begin(), sources.end(),
              [](const PixelSource& a, const PixelSource& b) {{
                  return a.flux > b.flux;
              }});

    return sources;
}}

// ---- Triangle Matching ---------------------------------------------

struct Triangle {{
    int idx[3];
    double sides[3];  // Sorted side lengths (normalized)
}};

std::vector<Triangle> build_triangles(const std::vector<PixelSource>& sources,
                                       int n_use = 30) {{
    std::vector<Triangle> triangles;
    int n = std::min((int)sources.size(), n_use);

    for (int i = 0; i < n; i++) {{
        for (int j = i+1; j < n; j++) {{
            for (int k = j+1; k < n; k++) {{
                Triangle t;
                t.idx[0] = i; t.idx[1] = j; t.idx[2] = k;

                double d01 = hypot(sources[i].x - sources[j].x,
                                   sources[i].y - sources[j].y);
                double d02 = hypot(sources[i].x - sources[k].x,
                                   sources[i].y - sources[k].y);
                double d12 = hypot(sources[j].x - sources[k].x,
                                   sources[j].y - sources[k].y);

                // Normalize by longest side
                double maxd = std::max({{d01, d02, d12}});
                t.sides[0] = d01 / maxd;
                t.sides[1] = d02 / maxd;
                t.sides[2] = d12 / maxd;
                std::sort(t.sides, t.sides + 3);

                triangles.push_back(t);
            }}
        }}
    }}
    return triangles;
}}

double triangle_distance(const Triangle& a, const Triangle& b) {{
    return sqrt(pow(a.sides[0]-b.sides[0], 2) +
                pow(a.sides[1]-b.sides[1], 2) +
                pow(a.sides[2]-b.sides[2], 2));
}}

// ---- WCS Fitting ---------------------------------------------------

WCSSolution fit_wcs(const std::vector<std::pair<PixelSource, CatalogStar>>& matches) {{
    WCSSolution wcs = {{}};
    int n = (int)matches.size();
    if (n < MIN_MATCH_STARS) {{
        wcs.valid = false;
        return wcs;
    }}

    // Linear least-squares: solve for CD matrix
    // RA  = crval1 + cd00*(x-crpix1) + cd01*(y-crpix2)
    // Dec = crval2 + cd10*(x-crpix1) + cd11*(y-crpix2)
    wcs.crpix1 = matches[0].first.x;
    wcs.crpix2 = matches[0].first.y;
    wcs.crval1 = matches[0].second.ra_deg;
    wcs.crval2 = matches[0].second.dec_deg;

    // Normal equations (2x2 system for each axis)
    double sxx=0, sxy=0, syy=0, sxra=0, syra=0, sxdec=0, sydec=0;
    for (const auto& m : matches) {{
        double dx = m.first.x - wcs.crpix1;
        double dy = m.first.y - wcs.crpix2;
        double dra = m.second.ra_deg - wcs.crval1;
        double ddec = m.second.dec_deg - wcs.crval2;
        sxx += dx*dx; sxy += dx*dy; syy += dy*dy;
        sxra += dx*dra; syra += dy*dra;
        sxdec += dx*ddec; sydec += dy*ddec;
    }}

    double det = sxx*syy - sxy*sxy;
    if (fabs(det) < 1e-20) {{ wcs.valid = false; return wcs; }}

    wcs.cd[0][0] = (syy*sxra - sxy*syra) / det;
    wcs.cd[0][1] = (sxx*syra - sxy*sxra) / det;
    wcs.cd[1][0] = (syy*sxdec - sxy*sydec) / det;
    wcs.cd[1][1] = (sxx*sydec - sxy*sxdec) / det;
    wcs.order = 1;

    // Compute residuals
    double sum_res2 = 0;
    for (const auto& m : matches) {{
        double ra_calc, dec_calc;
        wcs.pixel_to_sky(m.first.x, m.first.y, ra_calc, dec_calc);
        double dra = (ra_calc - m.second.ra_deg) * 3600 *
                     cos(m.second.dec_deg * M_PI / 180);
        double ddec = (dec_calc - m.second.dec_deg) * 3600;
        sum_res2 += dra*dra + ddec*ddec;
    }}

    wcs.residual_arcsec = sqrt(sum_res2 / n);
    wcs.n_matched_stars = n;
    wcs.valid = (wcs.residual_arcsec < MAX_RESIDUAL_ARCSEC);

    printf("[PlateSolver] Solution: %d stars matched, residual %.3f arcsec [%s]\\n",
           n, wcs.residual_arcsec, wcs.valid ? "VALID" : "FAILED");

    return wcs;
}}
'''

    filepath.write_text(code, encoding="utf-8")
    lines = len(code.splitlines())
    register_artifact(task["id"], AGENT_ID, str(filepath), "cpp", lines, "1.0")
    log_action(AGENT_ID, "GENERATE_CODE", task["id"],
               details={"file": str(filepath), "lines": lines, "kb_queries": ["plate_solution", "psf_gaussian"]},
               files_modified=[str(filepath)], status="SUCCESS")
    print(f"           -> Generated plate_solver.cpp ({lines} lines)")
    return True


def generate_photometry(task):
    OUTPUT_PATH.mkdir(parents=True, exist_ok=True)
    filepath = OUTPUT_PATH / "photometry.cpp"
    eq = query_equation("psf_gaussian")
    mag_eq = query_equation("magnitude")

    code = f'''/**
 * photometry.cpp - SentinelForge Edge Pipeline
 * PSF fitting photometry and magnitude measurement.
 * Equation: {eq.get("formula", "Gaussian PSF")}
 * Generated by Agent 3 (Plate Solver)
 */

#include <cstdio>
#include <cmath>
#include <vector>

constexpr double FWHM_DEFAULT  = {eq.get("typical_fwhm_px", 2.5)};
constexpr int    APERTURE_RADII[] = {{3, 5, 8}};  // pixels
constexpr double ZERO_POINT_MAG   = 25.0;         // Instrumental zero point

struct PhotometryResult {{
    double x, y;                // Sub-pixel centroid
    double flux_aper[3];        // Aperture photometry at 3 radii
    double flux_psf;            // PSF-fitted flux
    double mag_inst;            // Instrumental magnitude
    double mag_err;             // Magnitude uncertainty
    double snr;
    double fwhm_measured;
    double background_local;
    bool saturated;
}};

class Photometer {{
public:
    /**
     * Aperture photometry: sum flux in circular aperture,
     * subtract background from annulus.
     */
    static PhotometryResult measure(const float* frame, int width, int height,
                                     double cx, double cy) {{
        PhotometryResult r = {{}};
        r.x = cx;
        r.y = cy;
        r.saturated = false;

        // Background from annulus (r=10 to r=15 pixels)
        double bg_sum = 0;
        int bg_count = 0;
        for (int dy = -15; dy <= 15; dy++) {{
            for (int dx = -15; dx <= 15; dx++) {{
                double dist = sqrt(dx*dx + dy*dy);
                if (dist < 10 || dist > 15) continue;
                int px = (int)cx + dx, py = (int)cy + dy;
                if (px < 0 || px >= width || py < 0 || py >= height) continue;
                bg_sum += frame[py * width + px];
                bg_count++;
            }}
        }}
        r.background_local = (bg_count > 0) ? bg_sum / bg_count : 0;

        // Aperture photometry at multiple radii
        for (int ai = 0; ai < 3; ai++) {{
            int aper = APERTURE_RADII[ai];
            double flux = 0;
            int n_pix = 0;
            for (int dy = -aper; dy <= aper; dy++) {{
                for (int dx = -aper; dx <= aper; dx++) {{
                    if (dx*dx + dy*dy > aper*aper) continue;
                    int px = (int)cx + dx, py = (int)cy + dy;
                    if (px < 0 || px >= width || py < 0 || py >= height) continue;
                    double val = frame[py * width + px] - r.background_local;
                    flux += val;
                    n_pix++;
                    if (frame[py * width + px] >= 65535) r.saturated = true;
                }}
            }}
            r.flux_aper[ai] = flux;
        }}

        // Use middle aperture for magnitude
        r.flux_psf = r.flux_aper[1];
        if (r.flux_psf > 0) {{
            r.mag_inst = ZERO_POINT_MAG - 2.5 * log10(r.flux_psf);
            double noise = sqrt(r.flux_psf + M_PI * 25 *
                               (r.background_local + 10*10));
            r.snr = r.flux_psf / noise;
            r.mag_err = 1.0857 / r.snr;  // Pogson error
        }} else {{
            r.mag_inst = 99.9;
            r.snr = 0;
            r.mag_err = 99.9;
        }}

        r.fwhm_measured = FWHM_DEFAULT;
        return r;
    }}
}};
'''

    filepath.write_text(code, encoding="utf-8")
    lines = len(code.splitlines())
    register_artifact(task["id"], AGENT_ID, str(filepath), "cpp", lines, "1.0")
    log_action(AGENT_ID, "GENERATE_CODE", task["id"],
               details={"file": str(filepath), "lines": lines},
               files_modified=[str(filepath)], status="SUCCESS")
    print(f"           -> Generated photometry.cpp ({lines} lines)")
    return True
