"""
SentinelForge Agent 8: Anomaly Hunter
Generates anomaly detection and object characterization modules.
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from pathlib import Path
from config import OUTPUT_DIR
from db import log_action, register_artifact
from knowledge import query_equation

AGENT_ID = 8
OUTPUT_PATH = OUTPUT_DIR / "builds" / "src"


def execute(task):
    OUTPUT_PATH.mkdir(parents=True, exist_ok=True)
    filepath = OUTPUT_PATH / "anomaly_detect.py"
    
    code = '''"""
anomaly_detect.py - SentinelForge Edge Pipeline
Flags uncorrelated tracks, detects maneuvers, breakup events,
and characterizes objects from light curves.
Generated by Agent 8 (Anomaly Hunter)
"""
import math
import json
import time
from dataclasses import dataclass, asdict
from typing import List, Optional
from enum import Enum


class AnomalyType(Enum):
    NEW_OBJECT      = "new_object"
    MANEUVER        = "maneuver"
    BREAKUP         = "breakup"
    REENTRY         = "reentry"
    BRIGHTNESS_CHANGE = "brightness_change"
    ATTITUDE_CHANGE = "attitude_change"


class ObjectClass(Enum):
    ACTIVE_SATELLITE = "3-axis stabilized active satellite"
    ROCKET_BODY      = "cylindrical rocket body"
    TUMBLING_DEBRIS  = "tumbling debris fragment"
    UNKNOWN          = "unknown - needs more data"


@dataclass
class Anomaly:
    anomaly_type: str
    severity: str           # "LOW", "MEDIUM", "HIGH", "CRITICAL"
    description: str
    detection_idx: int
    confidence: float
    timestamp: float
    details: dict


@dataclass
class LightCurvePoint:
    timestamp: float
    magnitude: float
    phase_angle_deg: float
    filter_name: str = "clear"


class AnomalyDetector:
    """Detect anomalous behavior in space object observations."""

    def __init__(self):
        self.history = {}   # norad_id -> list of observations
        self.anomalies: List[Anomaly] = []

    def analyze_uncorrelated(self, uncorrelated_indices: list,
                              detections: list) -> List[Anomaly]:
        """Flag detections that don't match any known catalog object."""
        anomalies = []
        for idx in uncorrelated_indices:
            det = detections[idx] if idx < len(detections) else {}

            # Check if it's likely a star (no angular rate)
            rate = det.get("angular_rate_arcsec_s", 0)
            if rate < 0.1:
                continue  # Probably a faint star not in catalog

            severity = "HIGH" if rate > 10 else "MEDIUM"

            anomalies.append(Anomaly(
                anomaly_type=AnomalyType.NEW_OBJECT.value,
                severity=severity,
                description=f"Uncorrelated track: rate={rate:.1f} arcsec/s, "
                           f"mag={det.get('magnitude', '?')}",
                detection_idx=idx,
                confidence=0.8 if rate > 5 else 0.5,
                timestamp=time.time(),
                details={
                    "ra_deg": det.get("ra_deg"),
                    "dec_deg": det.get("dec_deg"),
                    "angular_rate": rate,
                    "magnitude": det.get("magnitude"),
                    "streak_length": det.get("streak_length_arcsec", 0)
                }
            ))

        self.anomalies.extend(anomalies)
        return anomalies

    def detect_maneuver(self, norad_id: int, observed_ra: float,
                        observed_dec: float, predicted_ra: float,
                        predicted_dec: float, sigma_ra: float,
                        sigma_dec: float) -> Optional[Anomaly]:
        """Detect if an object has maneuvered (position deviates from prediction)."""
        dra = (observed_ra - predicted_ra) * 3600 * math.cos(math.radians(observed_dec))
        ddec = (observed_dec - predicted_dec) * 3600

        # Mahalanobis distance
        d = math.sqrt((dra/max(sigma_ra, 0.1))**2 + (ddec/max(sigma_dec, 0.1))**2)

        # Maneuver threshold: > 10 sigma deviation
        if d > 10:
            anomaly = Anomaly(
                anomaly_type=AnomalyType.MANEUVER.value,
                severity="CRITICAL",
                description=f"Object {norad_id} deviated {d:.1f} sigma from prediction. "
                           f"Likely maneuver.",
                detection_idx=-1,
                confidence=min(0.99, 1 - math.exp(-d/5)),
                timestamp=time.time(),
                details={
                    "norad_id": norad_id,
                    "deviation_sigma": d,
                    "offset_ra_arcsec": dra,
                    "offset_dec_arcsec": ddec
                }
            )
            self.anomalies.append(anomaly)
            return anomaly
        return None

    def detect_breakup(self, detections: list, 
                       correlation_results: list) -> List[Anomaly]:
        """Detect potential breakup: cluster of uncorrelated tracks near a known object."""
        uncorr = [d for d, c in zip(detections, correlation_results)
                  if c.get("status") == "uncorrelated"]

        if len(uncorr) < 3:
            return []

        # Check spatial clustering
        clusters = self._cluster_detections(uncorr, radius_deg=0.5)
        anomalies = []

        for cluster in clusters:
            if len(cluster) >= 3:
                avg_ra = sum(d.get("ra_deg", 0) for d in cluster) / len(cluster)
                avg_dec = sum(d.get("dec_deg", 0) for d in cluster) / len(cluster)

                anomaly = Anomaly(
                    anomaly_type=AnomalyType.BREAKUP.value,
                    severity="CRITICAL",
                    description=f"Potential breakup: {len(cluster)} uncorrelated "
                               f"objects clustered near RA={avg_ra:.2f} Dec={avg_dec:.2f}",
                    detection_idx=-1,
                    confidence=min(0.95, len(cluster) / 10.0),
                    timestamp=time.time(),
                    details={
                        "n_fragments": len(cluster),
                        "center_ra": avg_ra,
                        "center_dec": avg_dec,
                        "fragment_positions": [
                            {"ra": d.get("ra_deg"), "dec": d.get("dec_deg")}
                            for d in cluster
                        ]
                    }
                )
                anomalies.append(anomaly)

        self.anomalies.extend(anomalies)
        return anomalies

    def _cluster_detections(self, detections: list, radius_deg: float) -> list:
        """Simple single-linkage clustering by angular distance."""
        assigned = [False] * len(detections)
        clusters = []

        for i in range(len(detections)):
            if assigned[i]:
                continue
            cluster = [detections[i]]
            assigned[i] = True

            for j in range(i+1, len(detections)):
                if assigned[j]:
                    continue
                for c in cluster:
                    dist = math.sqrt(
                        (detections[j].get("ra_deg",0) - c.get("ra_deg",0))**2 +
                        (detections[j].get("dec_deg",0) - c.get("dec_deg",0))**2
                    )
                    if dist < radius_deg:
                        cluster.append(detections[j])
                        assigned[j] = True
                        break

            clusters.append(cluster)
        return clusters

    def characterize_object(self, light_curve: List[LightCurvePoint]) -> dict:
        """Classify object type from brightness time series (light curve)."""
        if len(light_curve) < 5:
            return {"classification": ObjectClass.UNKNOWN.value,
                    "reason": "insufficient data"}

        mags = [p.magnitude for p in light_curve]
        times = [p.timestamp for p in light_curve]
        amplitude = max(mags) - min(mags)

        # Estimate period via autocorrelation
        period = self._estimate_period(times, mags)

        if amplitude < 0.3 and (period is None or period > 100):
            classification = ObjectClass.ACTIVE_SATELLITE.value
        elif amplitude > 1.0 and period is not None and period < 10:
            classification = ObjectClass.TUMBLING_DEBRIS.value
        elif amplitude > 0.5 and period is not None:
            classification = ObjectClass.ROCKET_BODY.value
        else:
            classification = ObjectClass.UNKNOWN.value

        return {
            "classification": classification,
            "amplitude_mag": round(amplitude, 3),
            "period_sec": round(period, 2) if period else None,
            "n_observations": len(light_curve),
            "mean_magnitude": round(sum(mags)/len(mags), 3)
        }

    def _estimate_period(self, times: list, values: list) -> Optional[float]:
        """Simple autocorrelation period estimation."""
        n = len(values)
        if n < 10:
            return None

        mean = sum(values) / n
        centered = [v - mean for v in values]

        best_lag = None
        best_corr = -1

        dt_mean = (times[-1] - times[0]) / (n - 1)

        for lag in range(2, n // 2):
            corr = sum(centered[i] * centered[i+lag]
                      for i in range(n - lag))
            corr /= max(sum(c**2 for c in centered), 1e-10)

            if corr > best_corr:
                best_corr = corr
                best_lag = lag

        if best_lag and best_corr > 0.3:
            return best_lag * dt_mean
        return None

    def get_alerts(self, min_severity: str = "MEDIUM") -> List[Anomaly]:
        """Get anomalies above severity threshold."""
        severity_order = {"LOW": 0, "MEDIUM": 1, "HIGH": 2, "CRITICAL": 3}
        threshold = severity_order.get(min_severity, 1)
        return [a for a in self.anomalies
                if severity_order.get(a.severity, 0) >= threshold]
'''

    filepath.write_text(code, encoding="utf-8")
    lines = len(code.splitlines())
    register_artifact(task["id"], AGENT_ID, str(filepath), "python", lines, "1.0")
    log_action(AGENT_ID, "GENERATE_CODE", task["id"],
               details={"file": str(filepath), "lines": lines},
               files_modified=[str(filepath)], status="SUCCESS")
    print(f"           -> Generated anomaly_detect.py ({lines} lines)")
    return True
