"""
SentinelForge Agent 7: Correlator
Generates catalog matching module using Mahalanobis distance.
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from pathlib import Path
from config import PIPELINE_SPEC, OUTPUT_DIR
from db import log_action, register_artifact

AGENT_ID = 7
OUTPUT_PATH = OUTPUT_DIR / "builds" / "src"


def execute(task):
    OUTPUT_PATH.mkdir(parents=True, exist_ok=True)
    filepath = OUTPUT_PATH / "correlator.py"
    maha_max = PIPELINE_SPEC["correlation_mahalanobis_max"]

    code = f'''"""
correlator.py - SentinelForge Edge Pipeline
Matches detections against local space object catalog using Mahalanobis distance.
Generated by Agent 7 (Correlator)
"""
import math
import json
import time
from dataclasses import dataclass, asdict
from typing import List, Tuple, Optional

MAHALANOBIS_THRESHOLD = {maha_max}


@dataclass
class CatalogObject:
    """Space object from local catalog mirror."""
    norad_id: int
    name: str
    ra_predicted_deg: float
    dec_predicted_deg: float
    sigma_ra_arcsec: float      # Position uncertainty in RA
    sigma_dec_arcsec: float     # Position uncertainty in Dec
    epoch: float                # Prediction epoch (Unix time)
    magnitude_expected: float
    object_type: str            # "payload", "rocket_body", "debris", "unknown"
    country: str
    last_observed: float        # Unix time of last observation


@dataclass
class CorrelationResult:
    """Result of matching a detection to catalog."""
    detection_idx: int
    norad_id: Optional[int]
    distance_mahalanobis: float
    status: str                 # "correlated", "ambiguous", "uncorrelated"
    confidence: float           # 0-1


class CatalogCorrelator:
    """Match detections to known space objects."""

    def __init__(self):
        self.catalog: List[CatalogObject] = []

    def load_catalog(self, catalog_path: str):
        """Load local catalog mirror (JSON format)."""
        try:
            with open(catalog_path, "r") as f:
                data = json.load(f)
            self.catalog = [CatalogObject(**obj) for obj in data]
            print(f"[Correlator] Loaded {{len(self.catalog)}} objects from catalog")
        except FileNotFoundError:
            print(f"[Correlator] No catalog found at {{catalog_path}} - starting empty")
            self.catalog = []

    def mahalanobis_distance(self, det_ra: float, det_dec: float,
                              cat_ra: float, cat_dec: float,
                              sigma_ra: float, sigma_dec: float) -> float:
        """
        2D Mahalanobis distance accounting for position uncertainty.
        Returns dimensionless distance (threshold at {maha_max}).
        """
        # Convert to arcseconds for comparison
        dra = (det_ra - cat_ra) * 3600 * math.cos(math.radians(det_dec))
        ddec = (det_dec - cat_dec) * 3600

        # Mahalanobis: d = sqrt((dra/sigma_ra)^2 + (ddec/sigma_dec)^2)
        if sigma_ra < 0.01:
            sigma_ra = 0.01
        if sigma_dec < 0.01:
            sigma_dec = 0.01

        d = math.sqrt((dra / sigma_ra)**2 + (ddec / sigma_dec)**2)
        return d

    def correlate(self, detections: list) -> Tuple[List[CorrelationResult],
                                                     List[int]]:
        """
        Match each detection against catalog.
        Returns: (correlation_results, uncorrelated_indices)
        """
        results = []
        uncorrelated = []

        for i, det in enumerate(detections):
            det_ra = det.get("ra_deg", 0)
            det_dec = det.get("dec_deg", 0)

            candidates = []
            for obj in self.catalog:
                d = self.mahalanobis_distance(
                    det_ra, det_dec,
                    obj.ra_predicted_deg, obj.dec_predicted_deg,
                    obj.sigma_ra_arcsec, obj.sigma_dec_arcsec
                )
                if d < MAHALANOBIS_THRESHOLD:
                    candidates.append((obj, d))

            if len(candidates) == 1:
                obj, d = candidates[0]
                confidence = max(0, 1.0 - d / MAHALANOBIS_THRESHOLD)
                results.append(CorrelationResult(
                    detection_idx=i, norad_id=obj.norad_id,
                    distance_mahalanobis=d, status="correlated",
                    confidence=confidence
                ))
            elif len(candidates) > 1:
                # Ambiguous - take closest
                candidates.sort(key=lambda x: x[1])
                obj, d = candidates[0]
                confidence = max(0, 0.5 * (1.0 - d / MAHALANOBIS_THRESHOLD))
                results.append(CorrelationResult(
                    detection_idx=i, norad_id=obj.norad_id,
                    distance_mahalanobis=d, status="ambiguous",
                    confidence=confidence
                ))
            else:
                results.append(CorrelationResult(
                    detection_idx=i, norad_id=None,
                    distance_mahalanobis=999.0, status="uncorrelated",
                    confidence=0.0
                ))
                uncorrelated.append(i)

        return results, uncorrelated

    def summary(self, results: List[CorrelationResult]) -> dict:
        """Generate correlation summary for upload."""
        return {{
            "total": len(results),
            "correlated": sum(1 for r in results if r.status == "correlated"),
            "ambiguous": sum(1 for r in results if r.status == "ambiguous"),
            "uncorrelated": sum(1 for r in results if r.status == "uncorrelated"),
            "timestamp": time.time()
        }}
'''

    filepath.write_text(code, encoding="utf-8")
    lines = len(code.splitlines())
    register_artifact(task["id"], AGENT_ID, str(filepath), "python", lines, "1.0")
    log_action(AGENT_ID, "GENERATE_CODE", task["id"],
               details={"file": str(filepath), "lines": lines},
               files_modified=[str(filepath)], status="SUCCESS")
    print(f"           -> Generated correlator.py ({lines} lines)")
    return True
