"""
SentinelForge Agent 6: ML Trainer
Generates PyTorch streak detection model training pipeline.
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
from pathlib import Path
from config import OUTPUT_DIR
from db import log_action, register_artifact

AGENT_ID = 6
OUTPUT_PATH = OUTPUT_DIR / "builds" / "src"

def execute(task):
    OUTPUT_PATH.mkdir(parents=True, exist_ok=True)
    filepath = OUTPUT_PATH / "train_model.py"
    code = '''"""
train_model.py - SentinelForge ML Pipeline
PyTorch streak detection model: trains on synthetic data, exports ONNX.
Generated by Agent 6 (ML Trainer)
"""
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import numpy as np
import json, os, time

class StreakDetectionNet(nn.Module):
    """Lightweight CNN for streak vs noise classification."""
    def __init__(self):
        super().__init__()
        self.features = nn.Sequential(
            nn.Conv2d(1, 32, 3, padding=1), nn.BatchNorm2d(32), nn.ReLU(),
            nn.MaxPool2d(2),
            nn.Conv2d(32, 64, 3, padding=1), nn.BatchNorm2d(64), nn.ReLU(),
            nn.MaxPool2d(2),
            nn.Conv2d(64, 128, 3, padding=1), nn.BatchNorm2d(128), nn.ReLU(),
            nn.AdaptiveAvgPool2d(4),
        )
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(128 * 4 * 4, 256), nn.ReLU(), nn.Dropout(0.3),
            nn.Linear(256, 64), nn.ReLU(),
            nn.Linear(64, 3)  # classes: noise, point_source, streak
        )

    def forward(self, x):
        return self.classifier(self.features(x))


class StreakDataset(Dataset):
    """Dataset of 64x64 cutouts: noise, stars, streaks."""
    def __init__(self, n_samples=10000):
        self.n = n_samples
        self.data = []
        self.labels = []
        for i in range(n_samples):
            label = i % 3
            patch = np.random.normal(100, 10, (64, 64)).astype(np.float32)
            if label == 1:  # star
                cx, cy = 32, 32
                for dy in range(-3, 4):
                    for dx in range(-3, 4):
                        r2 = dx**2 + dy**2
                        patch[cy+dy, cx+dx] += 500 * np.exp(-r2/3)
            elif label == 2:  # streak
                angle = np.random.uniform(0, np.pi)
                length = np.random.randint(10, 40)
                for k in range(-length//2, length//2):
                    px = int(32 + k * np.cos(angle))
                    py = int(32 + k * np.sin(angle))
                    if 0 <= px < 64 and 0 <= py < 64:
                        patch[py, px] += 200
            patch = (patch - patch.mean()) / (patch.std() + 1e-6)
            self.data.append(patch)
            self.labels.append(label)

    def __len__(self): return self.n
    def __getitem__(self, idx):
        x = torch.tensor(self.data[idx]).unsqueeze(0)
        y = torch.tensor(self.labels[idx])
        return x, y


def train(epochs=20, batch_size=64, lr=1e-3, output_dir="models"):
    os.makedirs(output_dir, exist_ok=True)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"[MLTrainer] Device: {device}")

    model = StreakDetectionNet().to(device)
    dataset = StreakDataset(n_samples=9000)
    val_dataset = StreakDataset(n_samples=1000)
    loader = DataLoader(dataset, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=batch_size)

    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=lr)
    scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=10, gamma=0.5)

    best_acc = 0
    for epoch in range(epochs):
        model.train()
        total_loss = 0
        for x, y in loader:
            x, y = x.to(device), y.to(device)
            optimizer.zero_grad()
            out = model(x)
            loss = criterion(out, y)
            loss.backward()
            optimizer.step()
            total_loss += loss.item()
        scheduler.step()

        # Validate
        model.eval()
        correct, total = 0, 0
        with torch.no_grad():
            for x, y in val_loader:
                x, y = x.to(device), y.to(device)
                pred = model(x).argmax(1)
                correct += (pred == y).sum().item()
                total += y.size(0)
        acc = correct / total
        print(f"  Epoch {epoch+1}/{epochs}: loss={total_loss/len(loader):.4f} val_acc={acc:.4f}")

        if acc > best_acc:
            best_acc = acc
            torch.save(model.state_dict(), f"{output_dir}/streak_det_best.pth")

    # Export ONNX
    model.eval()
    dummy = torch.randn(1, 1, 64, 64).to(device)
    onnx_path = f"{output_dir}/streak_det.onnx"
    torch.onnx.export(model, dummy, onnx_path, input_names=["image"],
                      output_names=["classification"], opset_version=17)
    print(f"[MLTrainer] Exported ONNX: {onnx_path}")
    print(f"[MLTrainer] Best val accuracy: {best_acc:.4f}")
    return {"best_accuracy": best_acc, "onnx_path": onnx_path}

if __name__ == "__main__":
    train()
'''
    filepath.write_text(code, encoding="utf-8")
    lines = len(code.splitlines())
    register_artifact(task["id"], AGENT_ID, str(filepath), "python", lines, "1.0")
    log_action(AGENT_ID, "GENERATE_CODE", task["id"],
               details={"file": str(filepath), "lines": lines},
               files_modified=[str(filepath)], status="SUCCESS")
    print(f"           -> Generated train_model.py ({lines} lines)")
    return True
