"""
SentinelForge Agent 5: Pipeline Orchestrator
Generates Python source extraction pipeline and observatory autonomous state machine.
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from pathlib import Path
from config import PIPELINE_SPEC, OUTPUT_DIR
from db import log_action, register_artifact

AGENT_ID = 5
OUTPUT_PATH = OUTPUT_DIR / "builds" / "src"


def execute(task):
    title = task.get("title", "").lower()
    if "source" in title or "extract" in title:
        return generate_source_extract(task)
    elif "state" in title or "autonom" in title or "observat" in title:
        return generate_autonomous(task)
    return generate_source_extract(task)


def generate_source_extract(task):
    OUTPUT_PATH.mkdir(parents=True, exist_ok=True)
    filepath = OUTPUT_PATH / "source_extract.py"

    code = f'''"""
source_extract.py - SentinelForge Edge Pipeline
Assembles detection tables from C++ pipeline outputs.
Applies plate solution (WCS) to convert pixel coords to sky coords.
Generated by Agent 5 (Pipeline Orchestrator)
"""
import json
import time
import struct
from dataclasses import dataclass, asdict
from typing import List, Optional
from pathlib import Path

SNR_THRESHOLD = {PIPELINE_SPEC["detection_snr_threshold"]}
MIN_STREAK_LEN = {PIPELINE_SPEC["streak_min_length_px"]}


@dataclass
class Detection:
    """Single detected source/streak in a telescope frame."""
    ra_deg: float           # Right Ascension (J2000, degrees)
    dec_deg: float          # Declination (J2000, degrees)
    ra_err_arcsec: float    # RA uncertainty
    dec_err_arcsec: float   # Dec uncertainty
    magnitude: float        # Instrumental magnitude
    snr: float              # Signal-to-noise ratio
    streak_length_arcsec: float  # 0 for point sources
    streak_angle_deg: float
    angular_rate_arcsec_s: float  # 0 for stationary objects
    pixel_x: float
    pixel_y: float
    timestamp_utc: float    # Unix epoch, microsecond precision
    exposure_sec: float
    frame_id: int
    sensor_id: str
    detection_type: str     # "point", "streak", "extended"


@dataclass
class WCSSolution:
    """World Coordinate System plate solution."""
    crpix1: float   # Reference pixel X
    crpix2: float   # Reference pixel Y
    crval1: float   # Reference RA (deg)
    crval2: float   # Reference Dec (deg)
    cd1_1: float    # Transformation matrix
    cd1_2: float
    cd2_1: float
    cd2_2: float
    residual_arcsec: float  # Plate solve fit quality

    def pixel_to_sky(self, x: float, y: float) -> tuple:
        dx = x - self.crpix1
        dy = y - self.crpix2
        ra = self.crval1 + self.cd1_1 * dx + self.cd1_2 * dy
        dec = self.crval2 + self.cd2_1 * dx + self.cd2_2 * dy
        return ra, dec


class SourceExtractor:
    """Assembles detection table from pipeline outputs."""

    def __init__(self, sensor_id: str):
        self.sensor_id = sensor_id
        self.detections: List[Detection] = []

    def process_frame(self, streak_data: list, point_data: list,
                      wcs: WCSSolution, frame_id: int,
                      timestamp: float, exposure: float) -> List[Detection]:
        """
        Merge streak detections and point source detections,
        apply WCS transform, and build detection table.
        """
        self.detections = []

        # Process streaks from GPU kernel output
        for s in streak_data:
            if s.get("snr", 0) < SNR_THRESHOLD:
                continue
            if s.get("length_px", 0) < MIN_STREAK_LEN:
                continue

            cx = (s["x_start"] + s["x_end"]) / 2
            cy = (s["y_start"] + s["y_end"]) / 2
            ra, dec = wcs.pixel_to_sky(cx, cy)

            # Compute angular rate from streak length and exposure
            plate_scale = abs(wcs.cd1_1) * 3600  # arcsec/pixel
            streak_arcsec = s["length_px"] * plate_scale
            angular_rate = streak_arcsec / exposure if exposure > 0 else 0

            det = Detection(
                ra_deg=ra, dec_deg=dec,
                ra_err_arcsec=wcs.residual_arcsec,
                dec_err_arcsec=wcs.residual_arcsec,
                magnitude=s.get("magnitude", -2.5 * __import__("math").log10(max(s.get("brightness", 1), 1))),
                snr=s["snr"],
                streak_length_arcsec=streak_arcsec,
                streak_angle_deg=s.get("angle_deg", 0),
                angular_rate_arcsec_s=angular_rate,
                pixel_x=cx, pixel_y=cy,
                timestamp_utc=timestamp,
                exposure_sec=exposure,
                frame_id=frame_id,
                sensor_id=self.sensor_id,
                detection_type="streak"
            )
            self.detections.append(det)

        # Process point sources (stationary)
        for p in point_data:
            if p.get("snr", 0) < SNR_THRESHOLD:
                continue

            ra, dec = wcs.pixel_to_sky(p["x"], p["y"])
            det = Detection(
                ra_deg=ra, dec_deg=dec,
                ra_err_arcsec=wcs.residual_arcsec * 0.5,
                dec_err_arcsec=wcs.residual_arcsec * 0.5,
                magnitude=p.get("magnitude", 0),
                snr=p["snr"],
                streak_length_arcsec=0,
                streak_angle_deg=0,
                angular_rate_arcsec_s=0,
                pixel_x=p["x"], pixel_y=p["y"],
                timestamp_utc=timestamp,
                exposure_sec=exposure,
                frame_id=frame_id,
                sensor_id=self.sensor_id,
                detection_type="point"
            )
            self.detections.append(det)

        return self.detections

    def to_json(self) -> str:
        return json.dumps([asdict(d) for d in self.detections], indent=2)

    def to_upload_package(self) -> dict:
        """Minimal package for cloud upload (~10KB per frame)."""
        return {{
            "sensor_id": self.sensor_id,
            "n_detections": len(self.detections),
            "detections": [asdict(d) for d in self.detections],
            "generated_at": time.time()
        }}
'''

    filepath.write_text(code, encoding="utf-8")
    lines = len(code.splitlines())
    register_artifact(task["id"], AGENT_ID, str(filepath), "python", lines, "1.0")
    log_action(AGENT_ID, "GENERATE_CODE", task["id"],
               details={"file": str(filepath), "lines": lines},
               files_modified=[str(filepath)], status="SUCCESS")
    print(f"           -> Generated source_extract.py ({lines} lines)")
    return True


def generate_autonomous(task):
    OUTPUT_PATH.mkdir(parents=True, exist_ok=True)
    filepath = OUTPUT_PATH / "autonomous.py"

    code = '''"""
autonomous.py - SentinelForge Edge Pipeline
Observatory autonomous control state machine.
Handles: dome, weather, scheduling, fault recovery, power monitoring.
Generated by Agent 5 (Pipeline Orchestrator)
"""
import time
import json
import logging
from enum import Enum, auto
from dataclasses import dataclass
from typing import Optional, Callable

logging.basicConfig(level=logging.INFO,
                    format="%(asctime)s [%(levelname)s] %(message)s")
log = logging.getLogger("autonomous")


class State(Enum):
    BOOT          = auto()
    IDLE          = auto()
    CALIBRATING   = auto()
    OPENING_DOME  = auto()
    OBSERVING     = auto()
    WEATHER_HOLD  = auto()
    CLOSING       = auto()
    DAWN_SHUTDOWN = auto()
    FAULTED       = auto()
    EMERGENCY     = auto()


@dataclass
class WeatherStatus:
    humidity_pct: float = 50.0
    wind_mph: float = 5.0
    cloud_cover_pct: float = 0.0
    rain: bool = False
    sky_brightness_mag: float = 21.5

    @property
    def safe_to_observe(self) -> bool:
        return (self.humidity_pct < 85 and
                self.wind_mph < 40 and
                self.cloud_cover_pct < 50 and
                not self.rain)


@dataclass
class ObservatoryHardware:
    """Interface to physical hardware (overridden per-site)."""
    dome_open: bool = False
    mount_parked: bool = True
    ccd_cooling: bool = False
    sun_altitude_deg: float = 10.0

    def open_dome(self):
        log.info("DOME: Opening")
        self.dome_open = True

    def close_dome(self):
        log.info("DOME: Closing")
        self.dome_open = False

    def park_mount(self):
        log.info("MOUNT: Parking")
        self.mount_parked = True

    def start_cooling(self):
        log.info("CCD: Cooling started")
        self.ccd_cooling = True


class ObservatoryController:
    """
    Autonomous observatory state machine.
    Runs the full night cycle: calibrate -> open -> observe -> close.
    Handles weather, faults, and power failures.
    """

    def __init__(self, site_id: str, hardware: ObservatoryHardware,
                 weather_fn: Callable[[], WeatherStatus],
                 sun_alt_fn: Callable[[], float]):
        self.site_id = site_id
        self.hw = hardware
        self.get_weather = weather_fn
        self.get_sun_alt = sun_alt_fn
        self.state = State.BOOT
        self.weather_hold_start = 0
        self.weather_hold_timeout = 1800  # 30 minutes
        self.frames_tonight = 0
        self.detections_tonight = 0
        self.faults = []

    def transition(self, new_state: State):
        log.info(f"STATE: {self.state.name} -> {new_state.name}")
        self.state = new_state

    def run(self, observe_fn: Callable, calibrate_fn: Callable):
        """Main loop - call this to run the full night."""
        log.info(f"=== Observatory {self.site_id} starting ===")

        while True:
            try:
                if self.state == State.BOOT:
                    self._boot()
                elif self.state == State.IDLE:
                    self._idle()
                elif self.state == State.CALIBRATING:
                    self._calibrate(calibrate_fn)
                elif self.state == State.OPENING_DOME:
                    self._open_dome()
                elif self.state == State.OBSERVING:
                    self._observe(observe_fn)
                elif self.state == State.WEATHER_HOLD:
                    self._weather_hold()
                elif self.state == State.CLOSING:
                    self._close()
                elif self.state == State.DAWN_SHUTDOWN:
                    self._dawn_shutdown()
                    break
                elif self.state == State.FAULTED:
                    self._handle_fault()
                elif self.state == State.EMERGENCY:
                    self._emergency_shutdown()
                    break
            except Exception as e:
                log.error(f"Exception in state {self.state.name}: {e}")
                self.faults.append(str(e))
                self.transition(State.FAULTED)

        log.info(f"=== Night complete: {self.frames_tonight} frames, "
                 f"{self.detections_tonight} detections ===")

    def _boot(self):
        log.info("Running system health check...")
        # Check: GPU, disk, camera, mount, dome, network
        self.hw.start_cooling()
        self.transition(State.IDLE)

    def _idle(self):
        sun_alt = self.get_sun_alt()
        if sun_alt < -12:  # Astronomical twilight
            self.transition(State.CALIBRATING)
        else:
            log.info(f"Waiting for dark (sun alt: {sun_alt:.1f} deg)")
            time.sleep(10)

    def _calibrate(self, calibrate_fn):
        log.info("Capturing calibration frames (darks + flats)")
        calibrate_fn()
        self.transition(State.OPENING_DOME)

    def _open_dome(self):
        weather = self.get_weather()
        if weather.safe_to_observe:
            self.hw.open_dome()
            self.transition(State.OBSERVING)
        else:
            log.warning(f"Weather unsafe: humidity={weather.humidity_pct}%, "
                       f"wind={weather.wind_mph}mph")
            self.weather_hold_start = time.time()
            self.transition(State.WEATHER_HOLD)

    def _observe(self, observe_fn):
        # Check sun
        if self.get_sun_alt() > -12:
            self.transition(State.CLOSING)
            return

        # Check weather every cycle
        weather = self.get_weather()
        if not weather.safe_to_observe:
            log.warning("Weather degraded - closing dome")
            self.hw.close_dome()
            self.weather_hold_start = time.time()
            self.transition(State.WEATHER_HOLD)
            return

        # Execute one observation cycle
        result = observe_fn()
        if result:
            self.frames_tonight += result.get("frames", 0)
            self.detections_tonight += result.get("detections", 0)

    def _weather_hold(self):
        elapsed = time.time() - self.weather_hold_start
        if elapsed > self.weather_hold_timeout:
            log.warning("Weather timeout - closing for the night")
            self.transition(State.CLOSING)
            return

        weather = self.get_weather()
        if weather.safe_to_observe:
            log.info("Weather cleared - resuming")
            self.hw.open_dome()
            self.transition(State.OBSERVING)
        else:
            time.sleep(60)

    def _close(self):
        self.hw.close_dome()
        self.hw.park_mount()
        self.transition(State.DAWN_SHUTDOWN)

    def _dawn_shutdown(self):
        log.info("Dawn shutdown - generating night report")
        self._generate_report()

    def _handle_fault(self):
        log.error(f"FAULT: {self.faults[-1] if self.faults else 'unknown'}")
        # Safe state: close dome, park mount
        self.hw.close_dome()
        self.hw.park_mount()
        # Try to recover after 5 minutes
        time.sleep(300)
        self.transition(State.IDLE)

    def _emergency_shutdown(self):
        log.critical("EMERGENCY SHUTDOWN")
        self.hw.close_dome()
        self.hw.park_mount()

    def _generate_report(self):
        report = {
            "site_id": self.site_id,
            "frames_captured": self.frames_tonight,
            "detections": self.detections_tonight,
            "faults": self.faults,
            "generated_at": time.time()
        }
        log.info(f"Night report: {json.dumps(report)}")
        return report

    def get_health_telemetry(self) -> dict:
        """Called every 60s by health beacon."""
        return {
            "site_id": self.site_id,
            "state": self.state.name,
            "dome_open": self.hw.dome_open,
            "mount_parked": self.hw.mount_parked,
            "frames_tonight": self.frames_tonight,
            "detections_tonight": self.detections_tonight,
            "faults": len(self.faults)
        }
'''

    filepath.write_text(code, encoding="utf-8")
    lines = len(code.splitlines())
    register_artifact(task["id"], AGENT_ID, str(filepath), "python", lines, "1.0")
    log_action(AGENT_ID, "GENERATE_CODE", task["id"],
               details={"file": str(filepath), "lines": lines},
               files_modified=[str(filepath)], status="SUCCESS")
    print(f"           -> Generated autonomous.py ({lines} lines)")
    return True
