/**
 * calibration.cu — SentinelForge Edge Pipeline
 * GPU-accelerated telescope frame calibration.
 *
 * Build: nvcc -O3 -arch=sm_87 calibration.cu -o calibration
 *        (sm_87 = Jetson AGX Orin)
 *
 * Generated by Agent 1 (Frame Architect)
 */
#include <cuda_runtime.h>
#include <cstdio>
#include <cmath>

constexpr int FRAME_W = 4096;
constexpr int FRAME_H = 4096;
constexpr int FRAME_PIXELS = FRAME_W * FRAME_H;
constexpr int TILE_SIZE = 64;
constexpr int TILES_X = FRAME_W / TILE_SIZE;
constexpr int TILES_Y = FRAME_H / TILE_SIZE;
constexpr int TOTAL_TILES = TILES_X * TILES_Y;
constexpr int SIGMA_CLIP_ITERS = 3;
constexpr float SIGMA_CLIP_THRESH = 3.0f;

/* Kernel 1: Subtract master dark frame (thermal noise removal).
   Clamp to zero — no negative ADU counts from Poisson underflow. */
__global__ void dark_subtract(float* __restrict__ frame,
                              const float* __restrict__ dark,
                              int n_pixels) {
    int idx = blockIdx.x * blockDim.x + threadIdx.x;
    if (idx >= n_pixels) return;
    frame[idx] = fmaxf(frame[idx] - dark[idx], 0.0f);
}

/* Kernel 2: Divide by normalized flat field (pixel sensitivity correction).
   flat_frame is pre-normalized so median(flat) = 1.0.
   Dead pixels (flat < 0.01) flagged as NaN. */
__global__ void flat_divide(float* __restrict__ frame,
                            const float* __restrict__ flat,
                            int n_pixels) {
    int idx = blockIdx.x * blockDim.x + threadIdx.x;
    if (idx >= n_pixels) return;
    float f = flat[idx];
    frame[idx] = (f > 0.01f) ? frame[idx] / f : nanf("");
}

/* Kernel 3a: Sigma-clipped median per 64x64 tile.
   One block per tile. Thread 0 performs serial median on 4096 pixels
   (fast enough — sort is ~16K comparisons per tile). */
__global__ void tile_background(const float* __restrict__ frame,
                                float* __restrict__ bg_tiles,
                                float* __restrict__ bg_sigma,
                                int width, int height) {
    int tile_x = blockIdx.x;
    int tile_y = blockIdx.y;
    if (tile_x >= TILES_X || tile_y >= TILES_Y) return;

    __shared__ float tile_data[TILE_SIZE * TILE_SIZE];
    int lid = threadIdx.x;

    /* Load pixel */
    int gx = tile_x * TILE_SIZE + (lid % TILE_SIZE);
    int gy = tile_y * TILE_SIZE + (lid / TILE_SIZE);
    tile_data[lid] = (gx < width && gy < height)
                     ? frame[gy * width + gx] : 0.0f;
    __syncthreads();

    /* Thread 0: sigma-clipped median */
    if (lid == 0) {
        float buf[TILE_SIZE * TILE_SIZE];
        int n = 0;
        for (int k = 0; k < TILE_SIZE * TILE_SIZE; k++) {
            float v = tile_data[k];
            if (!isnan(v)) buf[n++] = v;
        }

        float med = 0.0f, mad = 1.0f;
        for (int iter = 0; iter < SIGMA_CLIP_ITERS && n > 10; iter++) {
            /* Insertion sort for median */
            for (int a = 1; a < n; a++) {
                float key = buf[a]; int b = a - 1;
                while (b >= 0 && buf[b] > key) { buf[b+1] = buf[b]; b--; }
                buf[b+1] = key;
            }
            med = buf[n / 2];

            /* MAD */
            float devs[TILE_SIZE * TILE_SIZE];
            for (int k = 0; k < n; k++) devs[k] = fabsf(buf[k] - med);
            for (int a = 1; a < n; a++) {
                float key = devs[a]; int b = a - 1;
                while (b >= 0 && devs[b] > key) { devs[b+1] = devs[b]; b--; }
                devs[b+1] = key;
            }
            mad = 1.4826f * devs[n / 2];

            /* Reject outliers */
            float thresh = SIGMA_CLIP_THRESH * mad;
            int m = 0;
            for (int k = 0; k < n; k++)
                if (fabsf(buf[k] - med) <= thresh) buf[m++] = buf[k];
            n = m;
        }

        int idx = tile_y * TILES_X + tile_x;
        bg_tiles[idx] = med;
        bg_sigma[idx] = mad;
    }
}

/* Kernel 3b: Bicubic interpolation of tile grid + subtraction. */
__device__ float bicubic_w(float t) {
    t = fabsf(t);
    if (t <= 1.0f) return 1.5f*t*t*t - 2.5f*t*t + 1.0f;
    if (t <= 2.0f) return -0.5f*t*t*t + 2.5f*t*t - 4.0f*t + 2.0f;
    return 0.0f;
}

__global__ void subtract_background(float* __restrict__ frame,
                                     const float* __restrict__ bg_tiles,
                                     int width, int height) {
    int gx = blockIdx.x * blockDim.x + threadIdx.x;
    int gy = blockIdx.y * blockDim.y + threadIdx.y;
    if (gx >= width || gy >= height) return;

    float tx = ((float)gx / TILE_SIZE) - 0.5f;
    float ty = ((float)gy / TILE_SIZE) - 0.5f;
    int tx0 = (int)floorf(tx), ty0 = (int)floorf(ty);
    float fx = tx - tx0, fy = ty - ty0;

    float bg = 0.0f, wsum = 0.0f;
    for (int dy = -1; dy <= 2; dy++) {
        for (int dx = -1; dx <= 2; dx++) {
            int ttx = min(max(tx0+dx, 0), TILES_X-1);
            int tty = min(max(ty0+dy, 0), TILES_Y-1);
            float w = bicubic_w(fx-dx) * bicubic_w(fy-dy);
            bg += w * bg_tiles[tty * TILES_X + ttx];
            wsum += w;
        }
    }
    if (wsum > 0.0f) bg /= wsum;
    frame[gy * width + gx] -= bg;
}

/* Host entry point */
struct CalibResult {
    float mean_bg, bg_rms, time_ms;
};

extern "C" CalibResult calibrate_frame(
    float* d_frame, const float* d_dark, const float* d_flat,
    int width, int height)
{
    CalibResult r = {};
    cudaEvent_t t0, t1;
    cudaEventCreate(&t0); cudaEventCreate(&t1);
    cudaEventRecord(t0);

    int npx = width * height, bs = 256;
    int g1d = (npx + bs - 1) / bs;

    dark_subtract<<<g1d, bs>>>(d_frame, d_dark, npx);
    flat_divide<<<g1d, bs>>>(d_frame, d_flat, npx);

    float *d_bg, *d_sig;
    cudaMalloc(&d_bg, TOTAL_TILES * sizeof(float));
    cudaMalloc(&d_sig, TOTAL_TILES * sizeof(float));

    dim3 tg(TILES_X, TILES_Y);
    tile_background<<<tg, TILE_SIZE*TILE_SIZE>>>(d_frame, d_bg, d_sig, width, height);

    dim3 sb(16,16), sg((width+15)/16, (height+15)/16);
    subtract_background<<<sg, sb>>>(d_frame, d_bg, width, height);

    cudaEventRecord(t1); cudaEventSynchronize(t1);
    cudaEventElapsedTime(&r.time_ms, t0, t1);

    float h_bg[TOTAL_TILES];
    cudaMemcpy(h_bg, d_bg, TOTAL_TILES*sizeof(float), cudaMemcpyDeviceToHost);
    double s=0, s2=0;
    for (int i=0;i<TOTAL_TILES;i++){s+=h_bg[i]; s2+=h_bg[i]*h_bg[i];}
    r.mean_bg = (float)(s/TOTAL_TILES);
    r.bg_rms = (float)sqrt(s2/TOTAL_TILES - r.mean_bg*r.mean_bg);

    cudaFree(d_bg); cudaFree(d_sig);
    cudaEventDestroy(t0); cudaEventDestroy(t1);
    return r;
}
