"""
SentinelForge Agent 11: Shadow Validator
Compares edge pipeline results against cloud pipeline on real data.
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
from pathlib import Path
from config import OUTPUT_DIR
from db import log_action, register_artifact

AGENT_ID = 11
OUTPUT_PATH = OUTPUT_DIR / "builds" / "src"

def execute(task):
    OUTPUT_PATH.mkdir(parents=True, exist_ok=True)
    filepath = OUTPUT_PATH / "shadow_compare.py"
    code = '''"""
shadow_compare.py - SentinelForge Validation
Runs edge pipeline in parallel with cloud, compares results.
Generated by Agent 11 (Shadow Validator)
"""

class ShadowValidator:
    """Compare edge detections against cloud ground truth."""

    def __init__(self):
        self.comparisons = []

    def compare(self, edge_detections: list, cloud_detections: list,
                match_radius_arcsec: float = 2.0) -> dict:
        """Compare edge vs cloud detection lists."""
        matched = 0
        edge_only = 0
        cloud_only = 0
        edge_used = set()

        for c_det in cloud_detections:
            best_dist = float("inf")
            best_idx = -1
            for i, e_det in enumerate(edge_detections):
                if i in edge_used:
                    continue
                import math
                dra = (e_det.get("ra_deg",0) - c_det.get("ra_deg",0)) * 3600
                ddec = (e_det.get("dec_deg",0) - c_det.get("dec_deg",0)) * 3600
                dist = math.sqrt(dra**2 + ddec**2)
                if dist < best_dist:
                    best_dist = dist
                    best_idx = i
            if best_dist < match_radius_arcsec:
                matched += 1
                edge_used.add(best_idx)
            else:
                cloud_only += 1

        edge_only = len(edge_detections) - len(edge_used)

        result = {
            "matched": matched,
            "edge_only": edge_only,
            "cloud_only": cloud_only,
            "edge_completeness": matched / max(len(cloud_detections), 1),
            "edge_purity": matched / max(len(edge_detections), 1),
            "passed": cloud_only == 0
        }
        self.comparisons.append(result)

        status = "PASS" if result["passed"] else "FAIL"
        print(f"[ShadowValidator] matched={matched} edge_only={edge_only} "
              f"cloud_only={cloud_only} [{status}]")
        return result

    def summary(self) -> dict:
        if not self.comparisons:
            return {}
        n = len(self.comparisons)
        avg_comp = sum(c["edge_completeness"] for c in self.comparisons) / n
        avg_pur = sum(c["edge_purity"] for c in self.comparisons) / n
        all_pass = all(c["passed"] for c in self.comparisons)
        return {
            "n_frames": n,
            "avg_completeness": round(avg_comp, 4),
            "avg_purity": round(avg_pur, 4),
            "all_passed": all_pass
        }
'''
    filepath.write_text(code, encoding="utf-8")
    lines = len(code.splitlines())
    register_artifact(task["id"], AGENT_ID, str(filepath), "python", lines, "1.0")
    log_action(AGENT_ID, "GENERATE_CODE", task["id"],
               details={"file": str(filepath), "lines": lines},
               files_modified=[str(filepath)], status="SUCCESS")
    print(f"           -> Generated shadow_compare.py ({lines} lines)")
    return True
