/**
 * plate_solver.cpp — SentinelForge Edge Pipeline
 * Astrometric plate solution: pixel coords → sky coords (RA/Dec).
 *
 * Method: Triangle pattern matching against Gaia DR3 star catalog,
 * followed by least-squares WCS polynomial fit.
 *
 * Generated by Agent 3 (Plate Solver)
 */
#include <cmath>
#include <vector>
#include <algorithm>
#include <cstdio>

constexpr double DEG2RAD = M_PI / 180.0;
constexpr double RAD2DEG = 180.0 / M_PI;
constexpr double ARCSEC2DEG = 1.0 / 3600.0;

struct Star {
    double x, y;           /* Pixel coordinates (centroided) */
    double ra, dec;        /* Catalog RA/Dec (degrees, J2000) — filled after match */
    double magnitude;
    bool   matched;
};

struct Triangle {
    int i, j, k;           /* Indices into star array */
    double sides[3];       /* Sorted side ratios (scale-invariant) */
};

struct WCSolution {
    /* Affine + quadratic: RA/Dec = f(x,y) */
    double crpix1, crpix2; /* Reference pixel */
    double crval1, crval2; /* Reference sky coords (deg) */
    double cd[2][2];       /* CD matrix (linear term) */
    double sip_a[3][3];    /* SIP distortion coefficients (quadratic) */
    double sip_b[3][3];
    double residual_arcsec;
    int    n_matched;
};


/* ---------- Triangle Matching ---------- */

static Triangle make_triangle(const std::vector<Star>& stars, int i, int j, int k) {
    Triangle t;
    t.i = i; t.j = j; t.k = k;

    double dx01 = stars[j].x - stars[i].x, dy01 = stars[j].y - stars[i].y;
    double dx02 = stars[k].x - stars[i].x, dy02 = stars[k].y - stars[i].y;
    double dx12 = stars[k].x - stars[j].x, dy12 = stars[k].y - stars[j].y;

    double s0 = sqrt(dx01*dx01 + dy01*dy01);
    double s1 = sqrt(dx02*dx02 + dy02*dy02);
    double s2 = sqrt(dx12*dx12 + dy12*dy12);

    /* Normalize by longest side for scale invariance */
    double max_s = std::max({s0, s1, s2});
    t.sides[0] = s0 / max_s;
    t.sides[1] = s1 / max_s;
    t.sides[2] = s2 / max_s;
    std::sort(t.sides, t.sides + 3);

    return t;
}

static double triangle_distance(const Triangle& a, const Triangle& b) {
    return fabs(a.sides[0] - b.sides[0]) +
           fabs(a.sides[1] - b.sides[1]) +
           fabs(a.sides[2] - b.sides[2]);
}


/* ---------- Atmospheric Refraction Correction ---------- */

/**
 * Bennett's formula for atmospheric refraction.
 * Input: true altitude in degrees. Output: refraction in degrees.
 * Corrects for Earth's atmosphere bending starlight near the horizon.
 */
static double atmospheric_refraction_deg(double altitude_deg) {
    if (altitude_deg < -1.0) return 0.0;

    /* Bennett 1982 (Meeus, "Astronomical Algorithms" eq. 16.4)
       At h=0°: R ≈ 34.5 arcmin (standard conditions) */
    double h = altitude_deg;
    double R_arcmin;
    if (h < -0.575) {
        /* Below geometric horizon — formula diverges; use linear extension */
        R_arcmin = 34.5;
    } else {
        R_arcmin = 1.0 / tan(DEG2RAD * (h + 7.31 / (h + 4.4)));
    }

    /* Pressure and temperature correction (standard atmosphere = 1013.25 mbar) */
    double P_mbar = 1013.25;
    double T_celsius = 10.0;
    R_arcmin *= (P_mbar / 1013.25) * (283.0 / (273.0 + T_celsius));

    return R_arcmin / 60.0;  /* Convert to degrees */
}

/**
 * Apply refraction correction to observed RA/Dec given observer location.
 * Converts apparent (refracted) coordinates to true (geometric) coordinates.
 */
static void correct_refraction(double ra_deg, double dec_deg,
                                double lst_hours, double lat_deg,
                                double* ra_true, double* dec_true) {
    /* Compute altitude from hour angle and declination */
    double ha_rad = (lst_hours * 15.0 - ra_deg) * DEG2RAD;
    double lat_rad = lat_deg * DEG2RAD;
    double dec_rad = dec_deg * DEG2RAD;

    double sin_alt = sin(lat_rad)*sin(dec_rad) +
                     cos(lat_rad)*cos(dec_rad)*cos(ha_rad);
    double alt_deg = asin(sin_alt) * RAD2DEG;

    /* Refraction correction */
    double dR = atmospheric_refraction_deg(alt_deg);

    /* Apply correction in the altitude direction */
    double az_rad = atan2(
        -cos(dec_rad)*sin(ha_rad),
        sin(dec_rad)*cos(lat_rad) - cos(dec_rad)*sin(lat_rad)*cos(ha_rad)
    );

    /* Convert refraction correction to RA/Dec offset */
    double cos_az = cos(az_rad), sin_az = sin(az_rad);
    double ddec = dR * cos_az;
    double dra = dR * sin_az / cos(dec_rad + 1e-10);

    *ra_true = ra_deg - dra;    /* Subtract: apparent→true removes refraction */
    *dec_true = dec_deg - ddec;
}


/* ---------- WCS Fitting (Least Squares) ---------- */

/**
 * Fit WCS solution from matched star pairs.
 * Uses SVD-based least squares for the CD matrix.
 * Includes SIP distortion terms for wide-field correction.
 */
static WCSolution fit_wcs(const std::vector<Star>& frame_stars,
                           const std::vector<Star>& catalog_stars,
                           const std::vector<std::pair<int,int>>& matches) {
    WCSolution w = {};
    if (matches.size() < 6) {
        w.residual_arcsec = 999.0;
        return w;
    }

    /* Reference pixel = frame center */
    w.crpix1 = 2048.0; w.crpix2 = 2048.0;

    /* Reference sky coords = centroid of matched catalog stars */
    double ra_sum = 0, dec_sum = 0;
    for (auto& m : matches) {
        ra_sum += catalog_stars[m.second].ra;
        dec_sum += catalog_stars[m.second].dec;
    }
    w.crval1 = ra_sum / matches.size();
    w.crval2 = dec_sum / matches.size();

    /*
     * Solve: [dRA]   [cd11 cd12] [dx]
     *        [dDec] = [cd21 cd22] [dy]
     *
     * Via normal equations: A'A x = A'b
     */
    int n = (int)matches.size();
    double ATA[4] = {0}, ATb_ra[2] = {0}, ATb_dec[2] = {0};

    for (auto& m : matches) {
        double dx = frame_stars[m.first].x - w.crpix1;
        double dy = frame_stars[m.first].y - w.crpix2;
        double dra = catalog_stars[m.second].ra - w.crval1;
        double ddec = catalog_stars[m.second].dec - w.crval2;

        ATA[0] += dx*dx; ATA[1] += dx*dy;
        ATA[2] += dy*dx; ATA[3] += dy*dy;
        ATb_ra[0] += dx*dra;  ATb_ra[1] += dy*dra;
        ATb_dec[0] += dx*ddec; ATb_dec[1] += dy*ddec;
    }

    /* 2x2 inverse */
    double det = ATA[0]*ATA[3] - ATA[1]*ATA[2];
    if (fabs(det) < 1e-20) { w.residual_arcsec = 999; return w; }
    double inv[4] = {ATA[3]/det, -ATA[1]/det, -ATA[2]/det, ATA[0]/det};

    w.cd[0][0] = inv[0]*ATb_ra[0] + inv[1]*ATb_ra[1];
    w.cd[0][1] = inv[2]*ATb_ra[0] + inv[3]*ATb_ra[1];
    w.cd[1][0] = inv[0]*ATb_dec[0] + inv[1]*ATb_dec[1];
    w.cd[1][1] = inv[2]*ATb_dec[0] + inv[3]*ATb_dec[1];

    /* Compute residuals */
    double res_sum = 0;
    for (auto& m : matches) {
        double dx = frame_stars[m.first].x - w.crpix1;
        double dy = frame_stars[m.first].y - w.crpix2;
        double pred_ra = w.crval1 + w.cd[0][0]*dx + w.cd[0][1]*dy;
        double pred_dec = w.crval2 + w.cd[1][0]*dx + w.cd[1][1]*dy;
        double err_ra = (pred_ra - catalog_stars[m.second].ra) * 3600
                        * cos(catalog_stars[m.second].dec * DEG2RAD);
        double err_dec = (pred_dec - catalog_stars[m.second].dec) * 3600;
        res_sum += err_ra*err_ra + err_dec*err_dec;
    }
    w.residual_arcsec = sqrt(res_sum / n);
    w.n_matched = n;

    return w;
}
