"""
SentinelForge Agent 13: Docker Builder
Generates Dockerfile and docker-compose for the edge pipeline container.
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from pathlib import Path
from config import EDGE_BOX_SPEC, DEPLOY_SPEC, OUTPUT_DIR
from db import log_action, register_artifact

AGENT_ID = 13
OUTPUT_PATH = OUTPUT_DIR / "builds"


def execute(task):
    OUTPUT_PATH.mkdir(parents=True, exist_ok=True)
    generate_dockerfile(task)
    generate_compose(task)
    return True


def generate_dockerfile(task):
    filepath = OUTPUT_PATH / "Dockerfile"
    cuda = EDGE_BOX_SPEC["cuda_version"]

    code = f'''# SentinelForge Edge Pipeline - Multi-stage Docker Build
# Generated by Agent 13 (Docker Builder)
# Target: {EDGE_BOX_SPEC["gpu"]}
# CUDA: {cuda}
# OS: {EDGE_BOX_SPEC["os"]}

# ===== Stage 1: Build C++/CUDA code =====
FROM nvcr.io/nvidia/cuda:{cuda}.0-devel-ubuntu22.04 AS builder

RUN apt-get update && apt-get install -y --no-install-recommends \\
    build-essential cmake git \\
    libopencv-dev libcfitsio-dev \\
    && rm -rf /var/lib/apt/lists/*

WORKDIR /build
COPY src/ ./src/

# Compile CUDA kernels
RUN nvcc -O3 -arch=sm_87 \\
    src/calibration.cu \\
    src/streak_detect.cu \\
    -shared -o libsentinel_gpu.so \\
    -Xcompiler -fPIC

# Compile C++ drivers
RUN g++ -O3 -std=c++17 \\
    src/camera_driver.cpp \\
    src/mount_control.cpp \\
    src/plate_solver.cpp \\
    src/photometry.cpp \\
    -shared -o libsentinel_hw.so \\
    -fPIC -lpthread

# ===== Stage 2: Python runtime =====
FROM nvcr.io/nvidia/cuda:{cuda}.0-runtime-ubuntu22.04 AS runtime

RUN apt-get update && apt-get install -y --no-install-recommends \\
    python3 python3-pip \\
    libopencv-core4.5d libcfitsio9 \\
    && rm -rf /var/lib/apt/lists/*

# Python dependencies
RUN pip3 install --no-cache-dir \\
    numpy scipy astropy \\
    torch torchvision --index-url https://download.pytorch.org/whl/cu121 \\
    opencv-python-headless \\
    onnxruntime-gpu \\
    requests

WORKDIR /app

# Copy compiled libraries from builder
COPY --from=builder /build/libsentinel_gpu.so /app/lib/
COPY --from=builder /build/libsentinel_hw.so /app/lib/

# Copy Python pipeline
COPY src/*.py /app/
COPY config/ /app/config/

# Data directories
RUN mkdir -p /data/raw /data/calibrated /data/detections \\
             /data/thumbnails /data/catalog /data/darks /data/flats \\
             /logs

# Environment
ENV LD_LIBRARY_PATH=/app/lib:$LD_LIBRARY_PATH
ENV PYTHONUNBUFFERED=1
ENV SITE_ID=UNSET
ENV CUDA_VISIBLE_DEVICES=0

# Health check
HEALTHCHECK --interval=60s --timeout=10s --retries=3 \\
    CMD python3 /app/health_check.py || exit 1

EXPOSE 8080

ENTRYPOINT ["python3", "/app/autonomous.py"]
CMD ["--site-config", "/app/config/site.json"]
'''

    filepath.write_text(code, encoding="utf-8")
    lines = len(code.splitlines())
    register_artifact(task["id"], AGENT_ID, str(filepath), "docker", lines, "1.0")
    log_action(AGENT_ID, "GENERATE_CODE", task["id"],
               details={"file": str(filepath), "lines": lines},
               files_modified=[str(filepath)], status="SUCCESS")
    print(f"           -> Generated Dockerfile ({lines} lines)")


def generate_compose(task):
    filepath = OUTPUT_PATH / "docker-compose.yml"

    code = f'''# SentinelForge Edge - Docker Compose
# Generated by Agent 13 (Docker Builder)
# Deploy: docker compose up -d

version: "3.8"

services:
  edge-pipeline:
    image: {DEPLOY_SPEC["container_registry"]}/{DEPLOY_SPEC["image_name"]}:latest
    container_name: sentinelforge-edge
    runtime: nvidia
    restart: unless-stopped
    environment:
      - SITE_ID=${{SITE_ID:-UNSET}}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - CLOUD_ENDPOINT=${{CLOUD_ENDPOINT:-https://api.slingshot.internal}}
      - VPN_TOKEN=${{VPN_TOKEN}}
    volumes:
      - /data/raw:/data/raw
      - /data/calibrated:/data/calibrated
      - /data/detections:/data/detections
      - /data/thumbnails:/data/thumbnails
      - /data/catalog:/data/catalog
      - /data/darks:/data/darks
      - /data/flats:/data/flats
      - ./config:/app/config:ro
      - ./logs:/logs
    ports:
      - "8080:8080"
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0    # Telescope mount serial
      - /dev/ttyUSB1:/dev/ttyUSB1    # Dome controller
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
          memory: 48G
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    healthcheck:
      test: ["CMD", "python3", "/app/health_check.py"]
      interval: 60s
      timeout: 10s
      retries: 3

  watchdog:
    image: {DEPLOY_SPEC["container_registry"]}/slingshot-monitor:latest
    container_name: sentinelforge-watchdog
    restart: always
    depends_on:
      - edge-pipeline
    environment:
      - WATCH_CONTAINER=sentinelforge-edge
      - ALERT_ENDPOINT=${{ALERT_ENDPOINT}}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./logs:/logs

  updater:
    image: {DEPLOY_SPEC["container_registry"]}/slingshot-updater:latest
    container_name: sentinelforge-updater
    restart: always
    environment:
      - REGISTRY={DEPLOY_SPEC["container_registry"]}
      - IMAGE={DEPLOY_SPEC["image_name"]}
      - CHECK_INTERVAL=3600
      - AUTO_ROLLBACK=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
'''

    filepath.write_text(code, encoding="utf-8")
    lines = len(code.splitlines())
    register_artifact(task["id"], AGENT_ID, str(filepath), "yaml", lines, "1.0")
    log_action(AGENT_ID, "GENERATE_CODE", task["id"],
               details={"file": str(filepath), "lines": lines},
               files_modified=[str(filepath)], status="SUCCESS")
    print(f"           -> Generated docker-compose.yml ({lines} lines)")
