"""
SentinelForge Agent 14: Fleet Deployer
Pushes container images to remote observatory sites via VPN.
"""
import sys, os, json
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
from pathlib import Path
from config import SITES, DEPLOY_SPEC, OUTPUT_DIR
from db import log_action, register_artifact, record_deployment

AGENT_ID = 14
OUTPUT_PATH = OUTPUT_DIR / "builds" / "src"

def execute(task):
    OUTPUT_PATH.mkdir(parents=True, exist_ok=True)
    filepath = OUTPUT_PATH / "deploy.py"
    code = '''"""
deploy.py - SentinelForge Fleet Management
Pushes edge containers to remote observatory sites.
Canary -> Staged -> Full rollout with health checks.
Generated by Agent 14 (Fleet Deployer)
"""
import json, time, os

SITES = ''' + json.dumps(SITES, indent=4) + '''

DEPLOY_SPEC = ''' + json.dumps(DEPLOY_SPEC, indent=4) + '''


class FleetDeployer:
    """Manages rolling deployments across the observatory network."""

    def __init__(self):
        self.deploy_log = []

    def deploy_canary(self, image_version: str) -> bool:
        """Deploy to canary site first."""
        site_id = DEPLOY_SPEC["canary_site"]
        print(f"[Deployer] Canary deploy: {image_version} -> {site_id}")

        success = self._deploy_to_site(site_id, image_version)
        if not success:
            print(f"[Deployer] Canary FAILED at {site_id}")
            return False

        # Soak test
        soak_hours = DEPLOY_SPEC["canary_soak_hours"]
        print(f"[Deployer] Canary soak: {soak_hours}h at {site_id}")
        # In production: wait and check health
        # time.sleep(soak_hours * 3600)

        healthy = self._check_health(site_id)
        if not healthy:
            print(f"[Deployer] Canary unhealthy - rolling back")
            self._rollback_site(site_id)
            return False

        print(f"[Deployer] Canary PASSED at {site_id}")
        return True

    def deploy_staged(self, image_version: str) -> bool:
        """Deploy in batches after canary passes."""
        batch_size = DEPLOY_SPEC["staged_batch_size"]
        remaining = [s["id"] for s in SITES
                     if s["id"] != DEPLOY_SPEC["canary_site"]]

        for i in range(0, len(remaining), batch_size):
            batch = remaining[i:i+batch_size]
            print(f"[Deployer] Staged batch {i//batch_size + 1}: {batch}")

            for site_id in batch:
                success = self._deploy_to_site(site_id, image_version)
                if not success:
                    print(f"[Deployer] Failed at {site_id} - pausing rollout")
                    return False

            # Check batch health
            for site_id in batch:
                if not self._check_health(site_id):
                    print(f"[Deployer] Unhealthy: {site_id} - rolling back batch")
                    for sid in batch:
                        self._rollback_site(sid)
                    return False

            print(f"[Deployer] Batch {i//batch_size + 1} healthy")

        return True

    def deploy_full(self, image_version: str) -> bool:
        """Full deployment: canary -> staged -> all."""
        print(f"\\n{'='*50}")
        print(f"  FLEET DEPLOYMENT: {image_version}")
        print(f"  Strategy: {DEPLOY_SPEC['rollout_strategy']}")
        print(f"{'='*50}\\n")

        # Phase 1: Canary
        if not self.deploy_canary(image_version):
            return False

        # Phase 2: Staged rollout
        if not self.deploy_staged(image_version):
            return False

        print(f"\\n[Deployer] COMPLETE: {image_version} deployed to all sites")
        return True

    def _deploy_to_site(self, site_id: str, image_version: str) -> bool:
        """Push image to a single site via VPN tunnel."""
        print(f"  [{site_id}] Pulling {image_version}...")
        # In production: SSH over VPN, docker pull, docker compose up -d
        self.deploy_log.append({
            "site_id": site_id, "image": image_version,
            "status": "deployed", "timestamp": time.time()
        })
        return True

    def _check_health(self, site_id: str) -> bool:
        """Verify site is healthy post-deploy."""
        # In production: HTTP health endpoint check
        return True

    def _rollback_site(self, site_id: str):
        """Revert site to previous image version."""
        print(f"  [{site_id}] ROLLBACK")
        self.deploy_log.append({
            "site_id": site_id, "status": "rolled_back",
            "timestamp": time.time()
        })

    def get_report(self) -> dict:
        return {
            "total_sites": len(SITES),
            "deployed": sum(1 for d in self.deploy_log if d["status"] == "deployed"),
            "rolled_back": sum(1 for d in self.deploy_log if d["status"] == "rolled_back"),
            "log": self.deploy_log
        }
'''
    filepath.write_text(code, encoding="utf-8")
    lines = len(code.splitlines())
    register_artifact(task["id"], AGENT_ID, str(filepath), "python", lines, "1.0")
    log_action(AGENT_ID, "GENERATE_CODE", task["id"],
               details={"file": str(filepath), "lines": lines},
               files_modified=[str(filepath)], status="SUCCESS")
    print(f"           -> Generated deploy.py ({lines} lines)")
    return True
