"""
SentinelForge Agent 15: Site Monitor
Watches health telemetry from all remote observatory sites.
"""
import sys, os, json
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
from config import SITES, OUTPUT_DIR
from db import log_action, register_artifact

AGENT_ID = 15
OUTPUT_PATH = OUTPUT_DIR / "builds" / "src"

def execute(task):
    OUTPUT_PATH.mkdir(parents=True, exist_ok=True)
    filepath = OUTPUT_PATH / "monitor.py"
    code = '''"""
monitor.py - SentinelForge Fleet Monitoring
Real-time health dashboard for all observatory sites.
Generated by Agent 15 (Site Monitor)
"""
import json, time

class SiteMonitor:
    """Monitors health telemetry from all observatory sites."""

    def __init__(self, sites: list):
        self.sites = {s["id"]: s for s in sites}
        self.telemetry = {}
        self.alerts = []

    def update_telemetry(self, site_id: str, data: dict):
        """Receive health beacon from a site."""
        data["received_at"] = time.time()
        self.telemetry[site_id] = data
        self._check_alerts(site_id, data)

    def _check_alerts(self, site_id: str, data: dict):
        """Check for anomalous conditions."""
        # Site down (no beacon in 5 minutes)
        if data.get("state") == "FAULTED":
            self.alerts.append({
                "site": site_id, "severity": "HIGH",
                "message": f"{site_id} is in FAULTED state",
                "timestamp": time.time()
            })

        # GPU temperature
        gpu_temp = data.get("gpu_temp_c", 0)
        if gpu_temp > 85:
            self.alerts.append({
                "site": site_id, "severity": "HIGH",
                "message": f"{site_id} GPU temp {gpu_temp}C (max 85C)",
                "timestamp": time.time()
            })

        # Disk space
        disk_pct = data.get("disk_used_pct", 0)
        if disk_pct > 90:
            self.alerts.append({
                "site": site_id, "severity": "MEDIUM",
                "message": f"{site_id} disk {disk_pct}% full",
                "timestamp": time.time()
            })

        # Detection rate drop
        det_rate = data.get("detection_rate", 1.0)
        if det_rate < 0.5:
            self.alerts.append({
                "site": site_id, "severity": "HIGH",
                "message": f"{site_id} detection rate dropped to {det_rate:.0%}",
                "timestamp": time.time()
            })

    def dashboard(self):
        """Print fleet status dashboard."""
        print("\\n" + "="*70)
        print("  SENTINELFORGE FLEET MONITOR")
        print("="*70)
        for site_id in sorted(self.sites.keys()):
            t = self.telemetry.get(site_id, {})
            state = t.get("state", "OFFLINE")
            frames = t.get("frames_tonight", 0)
            detections = t.get("detections_tonight", 0)
            dome = "OPEN" if t.get("dome_open") else "CLOSED"
            age = time.time() - t.get("received_at", 0) if t else 999
            stale = " [STALE]" if age > 300 else ""
            print(f"  {site_id:8s} | {state:15s} | dome:{dome:6s} | "
                  f"frames:{frames:4d} | det:{detections:4d}{stale}")

        if self.alerts:
            print(f"\\n  ALERTS ({len(self.alerts)}):")
            for a in self.alerts[-10:]:
                print(f"    [{a['severity']}] {a['message']}")
        print("="*70)

    def get_stale_sites(self, timeout_sec=300) -> list:
        """Find sites that haven't reported in."""
        now = time.time()
        stale = []
        for site_id in self.sites:
            t = self.telemetry.get(site_id, {})
            if not t or (now - t.get("received_at", 0)) > timeout_sec:
                stale.append(site_id)
        return stale
'''
    filepath.write_text(code, encoding="utf-8")
    lines = len(code.splitlines())
    register_artifact(task["id"], AGENT_ID, str(filepath), "python", lines, "1.0")
    log_action(AGENT_ID, "GENERATE_CODE", task["id"],
               details={"file": str(filepath), "lines": lines},
               files_modified=[str(filepath)], status="SUCCESS")
    print(f"           -> Generated monitor.py ({lines} lines)")
    return True
