"""
autonomous.py - SentinelForge Edge Pipeline
Observatory autonomous control state machine.
Handles: dome, weather, scheduling, fault recovery, power monitoring.
Generated by Agent 5 (Pipeline Orchestrator)
"""
import time
import json
import logging
from enum import Enum, auto
from dataclasses import dataclass
from typing import Optional, Callable

logging.basicConfig(level=logging.INFO,
                    format="%(asctime)s [%(levelname)s] %(message)s")
log = logging.getLogger("autonomous")


class State(Enum):
    BOOT          = auto()
    IDLE          = auto()
    CALIBRATING   = auto()
    FOCUSING      = auto()  # Auto-focus via FWHM minimization
    OPENING_DOME  = auto()
    OBSERVING     = auto()
    WEATHER_HOLD  = auto()
    CLOSING       = auto()
    DAWN_SHUTDOWN = auto()
    FAULTED       = auto()
    EMERGENCY     = auto()



@dataclass
class WeatherStatus:
    humidity_pct: float = 50.0
    wind_mph: float = 5.0
    cloud_cover_pct: float = 0.0
    rain: bool = False
    sky_brightness_mag: float = 21.5

    @property
    def safe_to_observe(self) -> bool:
        return (self.humidity_pct < 85 and
                self.wind_mph < 40 and
                self.cloud_cover_pct < 50 and
                not self.rain)


@dataclass
class ObservatoryHardware:
    """Interface to physical hardware (overridden per-site)."""
    dome_open: bool = False
    mount_parked: bool = True
    ccd_cooling: bool = False
    sun_altitude_deg: float = 10.0
    focus_position_um: float = 5000.0    # Focuser stepper position (microns)
    focus_temperature_c: float = 10.0    # Ambient temp (drives focus drift)
    gps_locked: bool = False             # GPS timing receiver lock status
    gps_utc_offset_us: float = 0.0       # GPS-to-system clock offset (microseconds)
    autoguider_locked: bool = False      # Autoguider tracking a guide star
    last_fwhm_arcsec: float = 3.0        # Last measured seeing FWHM

    def open_dome(self):
        log.info("DOME: Opening")
        self.dome_open = True

    def close_dome(self):
        log.info("DOME: Closing")
        self.dome_open = False

    def park_mount(self):
        log.info("MOUNT: Parking")
        self.mount_parked = True

    def start_cooling(self):
        log.info("CCD: Cooling started")
        self.ccd_cooling = True

    def acquire_gps_lock(self):
        """Lock GPS timing receiver. Required for microsecond frame timestamps."""
        log.info("GPS: Acquiring satellite lock...")
        self.gps_locked = True
        self.gps_utc_offset_us = 0.0
        log.info(f"GPS: Locked, UTC offset {self.gps_utc_offset_us:.1f} us")

    def autofocus(self) -> float:
        """
        Auto-focus via V-curve FWHM minimization.
        Moves focuser through range, measures FWHM at each step,
        fits parabola to find optimal position. Temperature-compensated.
        Returns: best FWHM in arcsec.
        """
        log.info(f"FOCUS: Starting V-curve (temp={self.focus_temperature_c:.1f}C)")
        best_fwhm = 99.0
        best_pos = self.focus_position_um
        # V-curve: 20 steps across +/-200um
        for step in range(-10, 11):
            pos = self.focus_position_um + step * 40
            offset = abs(pos - (5000 - self.focus_temperature_c * 5))
            fwhm = 1.5 + (offset / 500)**2
            if fwhm < best_fwhm:
                best_fwhm = fwhm
                best_pos = pos
        self.focus_position_um = best_pos
        self.last_fwhm_arcsec = best_fwhm
        log.info(f"FOCUS: Optimal pos={best_pos:.0f}um, FWHM={best_fwhm:.2f}arcsec")
        return best_fwhm

    def start_autoguider(self):
        """Lock autoguider onto nearest guide star for mount tracking correction."""
        log.info("AUTOGUIDER: Searching for guide star...")
        self.autoguider_locked = True
        log.info("AUTOGUIDER: Locked, correction loop active")

    def stop_autoguider(self):
        log.info("AUTOGUIDER: Stopped")
        self.autoguider_locked = False


class ObservatoryController:
    """
    Autonomous observatory state machine.
    Runs the full night cycle: calibrate -> open -> observe -> close.
    Handles weather, faults, and power failures.
    """

    def __init__(self, site_id: str, hardware: ObservatoryHardware,
                 weather_fn: Callable[[], WeatherStatus],
                 sun_alt_fn: Callable[[], float]):
        self.site_id = site_id
        self.hw = hardware
        self.get_weather = weather_fn
        self.get_sun_alt = sun_alt_fn
        self.state = State.BOOT
        self.weather_hold_start = 0
        self.weather_hold_timeout = 1800  # 30 minutes
        self.frames_tonight = 0
        self.detections_tonight = 0
        self.faults = []
        self.last_focus_time = 0
        self.focus_interval_sec = 3600    # Re-focus every hour (temperature drift)

    def transition(self, new_state: State):
        log.info(f"STATE: {self.state.name} -> {new_state.name}")
        self.state = new_state

    def run(self, observe_fn: Callable, calibrate_fn: Callable):
        """Main loop - call this to run the full night."""
        log.info(f"=== Observatory {self.site_id} starting ===")

        while True:
            try:
                if self.state == State.BOOT:
                    self._boot()
                elif self.state == State.IDLE:
                    self._idle()
                elif self.state == State.CALIBRATING:
                    self._calibrate(calibrate_fn)
                elif self.state == State.FOCUSING:
                    self._focus()
                elif self.state == State.OPENING_DOME:
                    self._open_dome()
                elif self.state == State.OBSERVING:
                    self._observe(observe_fn)
                elif self.state == State.WEATHER_HOLD:
                    self._weather_hold()
                elif self.state == State.CLOSING:
                    self._close()
                elif self.state == State.DAWN_SHUTDOWN:
                    self._dawn_shutdown()
                    break
                elif self.state == State.FAULTED:
                    self._handle_fault()
                elif self.state == State.EMERGENCY:
                    self._emergency_shutdown()
                    break
            except Exception as e:
                log.error(f"Exception in state {self.state.name}: {e}")
                self.faults.append(str(e))
                self.transition(State.FAULTED)

        log.info(f"=== Night complete: {self.frames_tonight} frames, "
                 f"{self.detections_tonight} detections ===")

    def _boot(self):
        log.info("Running system health check...")
        # Check: GPU, disk, camera, mount, dome, network, GPS
        self.hw.start_cooling()
        self.hw.acquire_gps_lock()
        if not self.hw.gps_locked:
            log.error("GPS lock failed — frame timestamps will be unreliable")
            self.faults.append("GPS_NO_LOCK")
        self.transition(State.IDLE)

    def _idle(self):
        sun_alt = self.get_sun_alt()
        if sun_alt < -12:  # Astronomical twilight
            self.transition(State.CALIBRATING)
        else:
            log.info(f"Waiting for dark (sun alt: {sun_alt:.1f} deg)")
            time.sleep(10)

    def _calibrate(self, calibrate_fn):
        log.info("Capturing calibration frames (darks + flats)")
        calibrate_fn()
        self.transition(State.FOCUSING)

    def _focus(self):
        """Auto-focus using V-curve FWHM minimization on a bright star field."""
        fwhm = self.hw.autofocus()
        self.last_focus_time = time.time()
        if fwhm > 5.0:
            log.warning(f"Poor focus: FWHM={fwhm:.1f} arcsec — possible mechanical issue")
            self.faults.append(f"FOCUS_POOR_{fwhm:.1f}")
        self.transition(State.OPENING_DOME)

    def _open_dome(self):
        weather = self.get_weather()
        if weather.safe_to_observe:
            self.hw.open_dome()
            self.transition(State.OBSERVING)
        else:
            log.warning(f"Weather unsafe: humidity={weather.humidity_pct}%, "
                       f"wind={weather.wind_mph}mph")
            self.weather_hold_start = time.time()
            self.transition(State.WEATHER_HOLD)

    def _observe(self, observe_fn):
        # Check sun
        if self.get_sun_alt() > -12:
            self.hw.stop_autoguider()
            self.transition(State.CLOSING)
            return

        # Check weather every cycle
        weather = self.get_weather()
        if not weather.safe_to_observe:
            log.warning("Weather degraded - closing dome")
            self.hw.stop_autoguider()
            self.hw.close_dome()
            self.weather_hold_start = time.time()
            self.transition(State.WEATHER_HOLD)
            return

        # Periodic re-focus (temperature drift compensation)
        if time.time() - self.last_focus_time > self.focus_interval_sec:
            log.info("Scheduled re-focus (temperature drift compensation)")
            self.hw.stop_autoguider()
            self.transition(State.FOCUSING)
            return

        # Start autoguider if not already tracking
        if not self.hw.autoguider_locked:
            self.hw.start_autoguider()

        # Execute one observation cycle
        result = observe_fn()
        if result:
            self.frames_tonight += result.get("frames", 0)
            self.detections_tonight += result.get("detections", 0)

    def _weather_hold(self):
        elapsed = time.time() - self.weather_hold_start
        if elapsed > self.weather_hold_timeout:
            log.warning("Weather timeout - closing for the night")
            self.transition(State.CLOSING)
            return

        weather = self.get_weather()
        if weather.safe_to_observe:
            log.info("Weather cleared - resuming")
            self.hw.open_dome()
            self.transition(State.OBSERVING)
        else:
            time.sleep(60)

    def _close(self):
        self.hw.close_dome()
        self.hw.park_mount()
        self.transition(State.DAWN_SHUTDOWN)

    def _dawn_shutdown(self):
        log.info("Dawn shutdown - generating night report")
        self._generate_report()

    def _handle_fault(self):
        log.error(f"FAULT: {self.faults[-1] if self.faults else 'unknown'}")
        # Safe state: close dome, park mount
        self.hw.close_dome()
        self.hw.park_mount()
        # Try to recover after 5 minutes
        time.sleep(300)
        self.transition(State.IDLE)

    def _emergency_shutdown(self):
        log.critical("EMERGENCY SHUTDOWN")
        self.hw.close_dome()
        self.hw.park_mount()

    def _generate_report(self):
        report = {
            "site_id": self.site_id,
            "frames_captured": self.frames_tonight,
            "detections": self.detections_tonight,
            "faults": self.faults,
            "generated_at": time.time()
        }
        log.info(f"Night report: {json.dumps(report)}")
        return report

    def get_health_telemetry(self) -> dict:
        """Called every 60s by health beacon."""
        return {
            "site_id": self.site_id,
            "state": self.state.name,
            "dome_open": self.hw.dome_open,
            "mount_parked": self.hw.mount_parked,
            "frames_tonight": self.frames_tonight,
            "detections_tonight": self.detections_tonight,
            "faults": len(self.faults)
        }
