/**
 * background.cu — SentinelForge Edge Pipeline
 * GPU-accelerated sky background estimation and subtraction.
 * Uses sigma-clipped median on 64x64 tiles.
 * Generated by Agent 1 (Frame Architect)
 */

#include <cuda_runtime.h>
#include <cstdio>
#include <cmath>
#include <algorithm>

constexpr int TILE_SIZE    = 64;
constexpr int TILE_PIXELS  = TILE_SIZE * TILE_SIZE;  // 4096
constexpr float SIGMA_CLIP = 3.0f;
constexpr int CLIP_ITERS   = 3;

/**
 * Device function: Insertion sort for small arrays (in shared memory).
 * Used within each tile to compute median.
 */
__device__ void insertion_sort(float* arr, int n) {
    for (int i = 1; i < n; i++) {
        float key = arr[i];
        int j = i - 1;
        while (j >= 0 && arr[j] > key) {
            arr[j + 1] = arr[j];
            j--;
        }
        arr[j + 1] = key;
    }
}

/**
 * Kernel: Compute sigma-clipped median for each tile.
 * Each block handles one 64x64 tile.
 * Output: one background value per tile.
 */
__global__ void tile_median_kernel(
    const float* __restrict__ frame,
    float* __restrict__ bg_map,
    int frame_width, int frame_height,
    int tiles_x, int tiles_y
) {
    int tile_x = blockIdx.x;
    int tile_y = blockIdx.y;
    if (tile_x >= tiles_x || tile_y >= tiles_y) return;
    
    // Thread index within tile
    int tid = threadIdx.x;
    
    // Shared memory for tile pixels
    __shared__ float tile_data[TILE_PIXELS];
    __shared__ float valid_data[TILE_PIXELS];
    __shared__ int valid_count;
    
    // Load tile pixels into shared memory
    int px = tile_x * TILE_SIZE + (tid % TILE_SIZE);
    int py = tile_y * TILE_SIZE + (tid / TILE_SIZE);
    
    if (tid < TILE_PIXELS && px < frame_width && py < frame_height) {
        tile_data[tid] = frame[py * frame_width + px];
    } else if (tid < TILE_PIXELS) {
        tile_data[tid] = 0.0f;
    }
    __syncthreads();
    
    // Thread 0 performs sigma-clipped median
    if (tid == 0) {
        // Copy to working array
        int n = TILE_PIXELS;
        for (int i = 0; i < n; i++) valid_data[i] = tile_data[i];
        
        // Sigma clipping iterations
        for (int iter = 0; iter < CLIP_ITERS; iter++) {
            // Sort
            insertion_sort(valid_data, n);
            
            // Median
            float med = valid_data[n / 2];
            
            // MAD (Median Absolute Deviation)
            float deviations[TILE_PIXELS];
            for (int i = 0; i < n; i++)
                deviations[i] = fabsf(valid_data[i] - med);
            insertion_sort(deviations, n);
            float mad = 1.4826f * deviations[n / 2];
            
            // Reject outliers
            if (mad < 0.001f) break;  // All values identical
            int new_n = 0;
            for (int i = 0; i < n; i++) {
                if (fabsf(valid_data[i] - med) < SIGMA_CLIP * mad) {
                    valid_data[new_n++] = valid_data[i];
                }
            }
            if (new_n < 4) break;  // Too few pixels left
            n = new_n;
        }
        
        // Final median
        insertion_sort(valid_data, n);
        bg_map[tile_y * tiles_x + tile_x] = valid_data[n / 2];
    }
}

/**
 * Kernel: Bilinear upsample background map to full frame resolution.
 * Smooth interpolation avoids tiling artifacts.
 */
__global__ void upsample_background_kernel(
    const float* __restrict__ bg_map,
    float* __restrict__ bg_full,
    int frame_width, int frame_height,
    int tiles_x, int tiles_y
) {
    int x = blockIdx.x * blockDim.x + threadIdx.x;
    int y = blockIdx.y * blockDim.y + threadIdx.y;
    if (x >= frame_width || y >= frame_height) return;
    
    // Map pixel to tile coordinates (continuous)
    float tx = (float)x / TILE_SIZE - 0.5f;
    float ty = (float)y / TILE_SIZE - 0.5f;
    
    // Bilinear interpolation
    int tx0 = max(0, (int)floorf(tx));
    int ty0 = max(0, (int)floorf(ty));
    int tx1 = min(tiles_x - 1, tx0 + 1);
    int ty1 = min(tiles_y - 1, ty0 + 1);
    
    float fx = tx - floorf(tx);
    float fy = ty - floorf(ty);
    
    float v00 = bg_map[ty0 * tiles_x + tx0];
    float v10 = bg_map[ty0 * tiles_x + tx1];
    float v01 = bg_map[ty1 * tiles_x + tx0];
    float v11 = bg_map[ty1 * tiles_x + tx1];
    
    float result = v00 * (1-fx) * (1-fy) + v10 * fx * (1-fy)
                 + v01 * (1-fx) * fy     + v11 * fx * fy;
    
    bg_full[y * frame_width + x] = result;
}

/**
 * Kernel: Subtract background from science frame.
 */
__global__ void subtract_background_kernel(
    float* __restrict__ frame,
    const float* __restrict__ background,
    int width, int height
) {
    int x = blockIdx.x * blockDim.x + threadIdx.x;
    int y = blockIdx.y * blockDim.y + threadIdx.y;
    if (x >= width || y >= height) return;
    
    int idx = y * width + x;
    frame[idx] = fmaxf(0.0f, frame[idx] - background[idx]);
}

// ─── Host Interface ────────────────────────────────────────────

struct BackgroundBuffers {
    float* d_bg_map;
    float* d_bg_full;
    int tiles_x, tiles_y;
    
    bool allocate(int frame_width, int frame_height) {
        tiles_x = frame_width / TILE_SIZE;
        tiles_y = frame_height / TILE_SIZE;
        
        cudaMalloc(&d_bg_map, tiles_x * tiles_y * sizeof(float));
        cudaMalloc(&d_bg_full, frame_width * frame_height * sizeof(float));
        return true;
    }
    
    void release() {
        cudaFree(d_bg_map);
        cudaFree(d_bg_full);
    }
};

/**
 * SubtractBackground: Full background estimation and subtraction.
 */
bool SubtractBackground(
    float* d_frame,
    BackgroundBuffers& bufs,
    int width, int height,
    cudaStream_t stream = 0
) {
    // Step 1: Compute tiled sigma-clipped medians
    dim3 tile_grid(bufs.tiles_x, bufs.tiles_y);
    dim3 tile_block(TILE_PIXELS);  // One block per tile
    tile_median_kernel<<<tile_grid, tile_block, 0, stream>>>(
        d_frame, bufs.d_bg_map, width, height, bufs.tiles_x, bufs.tiles_y
    );
    
    // Step 2: Upsample to full resolution
    dim3 block(16, 16);
    dim3 grid((width + 15) / 16, (height + 15) / 16);
    upsample_background_kernel<<<grid, block, 0, stream>>>(
        bufs.d_bg_map, bufs.d_bg_full, width, height, bufs.tiles_x, bufs.tiles_y
    );
    
    // Step 3: Subtract
    subtract_background_kernel<<<grid, block, 0, stream>>>(
        d_frame, bufs.d_bg_full, width, height
    );
    
    return (cudaGetLastError() == cudaSuccess);
}
