/**
 * calibration.cu — SentinelForge Edge Pipeline
 * GPU-accelerated dark subtraction and flat field correction.
 * Generated by Agent 1 (Frame Architect)
 * 
 * Target: 4096x4096 @ 16-bit CCD frames
 * GPU: NVIDIA Jetson AGX Orin (CUDA 12.2)
 */

#include <cuda_runtime.h>
#include <cstdint>
#include <cstdio>
#include <cmath>

// ─── Error Checking Macro ──────────────────────────────────────
#define CUDA_CHECK(call) do { \
    cudaError_t err = call; \
    if (err != cudaSuccess) { \
        fprintf(stderr, "CUDA error at %s:%d: %s\n", \
                __FILE__, __LINE__, cudaGetErrorString(err)); \
        return false; \
    } \
} while(0)

// ─── Constants ─────────────────────────────────────────────────
constexpr int FRAME_WIDTH  = 4096;
constexpr int FRAME_HEIGHT = 4096;
constexpr int FRAME_PIXELS = FRAME_WIDTH * FRAME_HEIGHT;
constexpr int BLOCK_DIM    = 16;  // 16x16 = 256 threads per block

/**
 * Kernel: Dark Subtraction
 * Removes thermal noise pattern captured with shutter closed.
 * frame[i] = max(0, frame[i] - dark[i])
 */
__global__ void dark_subtract_kernel(
    float* __restrict__ frame,
    const float* __restrict__ dark,
    int width, int height
) {
    int x = blockIdx.x * blockDim.x + threadIdx.x;
    int y = blockIdx.y * blockDim.y + threadIdx.y;
    if (x >= width || y >= height) return;
    
    int idx = y * width + x;
    frame[idx] = fmaxf(0.0f, frame[idx] - dark[idx]);
}

/**
 * Kernel: Flat Field Division
 * Normalizes pixel-to-pixel sensitivity variations.
 * frame[i] = frame[i] / flat[i]
 * flat is pre-normalized to median=1.0
 */
__global__ void flat_divide_kernel(
    float* __restrict__ frame,
    const float* __restrict__ flat,
    int width, int height
) {
    int x = blockIdx.x * blockDim.x + threadIdx.x;
    int y = blockIdx.y * blockDim.y + threadIdx.y;
    if (x >= width || y >= height) return;
    
    int idx = y * width + x;
    float f = flat[idx];
    // Guard against dead pixels (flat=0)
    frame[idx] = (f > 0.001f) ? frame[idx] / f : 0.0f;
}

/**
 * Kernel: Convert uint16 raw to float32
 * CCD outputs 16-bit unsigned; pipeline works in float32.
 */
__global__ void uint16_to_float_kernel(
    const uint16_t* __restrict__ raw,
    float* __restrict__ out,
    int width, int height
) {
    int x = blockIdx.x * blockDim.x + threadIdx.x;
    int y = blockIdx.y * blockDim.y + threadIdx.y;
    if (x >= width || y >= height) return;
    
    int idx = y * width + x;
    out[idx] = static_cast<float>(raw[idx]);
}

// ─── Host Interface ────────────────────────────────────────────

/**
 * CalibrateFrame: Full calibration pipeline on GPU.
 * 
 * Steps:
 *   1. Convert uint16 raw → float32
 *   2. Subtract master dark frame
 *   3. Divide by master flat field
 * 
 * All buffers must be pre-allocated on GPU.
 * Returns false on CUDA error.
 */
bool CalibrateFrame(
    const uint16_t* d_raw,     // GPU: raw 16-bit frame
    float* d_frame,            // GPU: output float32 frame
    const float* d_dark,       // GPU: master dark (float32)
    const float* d_flat,       // GPU: master flat (float32, normalized)
    int width, int height,
    cudaStream_t stream = 0
) {
    dim3 block(BLOCK_DIM, BLOCK_DIM);
    dim3 grid((width + BLOCK_DIM - 1) / BLOCK_DIM,
              (height + BLOCK_DIM - 1) / BLOCK_DIM);
    
    // Step 1: uint16 → float32
    uint16_to_float_kernel<<<grid, block, 0, stream>>>(d_raw, d_frame, width, height);
    CUDA_CHECK(cudaGetLastError());
    
    // Step 2: Subtract dark
    dark_subtract_kernel<<<grid, block, 0, stream>>>(d_frame, d_dark, width, height);
    CUDA_CHECK(cudaGetLastError());
    
    // Step 3: Divide by flat
    flat_divide_kernel<<<grid, block, 0, stream>>>(d_frame, d_flat, width, height);
    CUDA_CHECK(cudaGetLastError());
    
    return true;
}

// ─── Master Frame Generation ───────────────────────────────────

/**
 * Kernel: Accumulate frames for master dark/flat creation.
 * Computes running sum for later averaging.
 */
__global__ void accumulate_kernel(
    float* __restrict__ accumulator,
    const float* __restrict__ frame,
    int width, int height
) {
    int x = blockIdx.x * blockDim.x + threadIdx.x;
    int y = blockIdx.y * blockDim.y + threadIdx.y;
    if (x >= width || y >= height) return;
    
    int idx = y * width + x;
    accumulator[idx] += frame[idx];
}

/**
 * Kernel: Divide accumulator by N to get average.
 */
__global__ void average_kernel(
    float* __restrict__ accumulator,
    int n_frames,
    int width, int height
) {
    int x = blockIdx.x * blockDim.x + threadIdx.x;
    int y = blockIdx.y * blockDim.y + threadIdx.y;
    if (x >= width || y >= height) return;
    
    int idx = y * width + x;
    accumulator[idx] /= static_cast<float>(n_frames);
}

/**
 * Kernel: Normalize flat field to median=1.0
 */
__global__ void normalize_flat_kernel(
    float* __restrict__ flat,
    float median_value,
    int width, int height
) {
    int x = blockIdx.x * blockDim.x + threadIdx.x;
    int y = blockIdx.y * blockDim.y + threadIdx.y;
    if (x >= width || y >= height) return;
    
    int idx = y * width + x;
    flat[idx] = (median_value > 0.0f) ? flat[idx] / median_value : 1.0f;
}

// ─── GPU Memory Manager ───────────────────────────────────────

struct CalibrationBuffers {
    float* d_frame;
    float* d_dark;
    float* d_flat;
    uint16_t* d_raw;
    int width;
    int height;
    
    bool allocate(int w, int h) {
        width = w;
        height = h;
        size_t float_bytes = w * h * sizeof(float);
        size_t raw_bytes = w * h * sizeof(uint16_t);
        
        CUDA_CHECK(cudaMalloc(&d_frame, float_bytes));
        CUDA_CHECK(cudaMalloc(&d_dark, float_bytes));
        CUDA_CHECK(cudaMalloc(&d_flat, float_bytes));
        CUDA_CHECK(cudaMalloc(&d_raw, raw_bytes));
        
        printf("[CalibrationBuffers] Allocated %.1f MB GPU memory\n",
               (float_bytes * 3 + raw_bytes) / (1024.0f * 1024.0f));
        return true;
    }
    
    void release() {
        cudaFree(d_frame);
        cudaFree(d_dark);
        cudaFree(d_flat);
        cudaFree(d_raw);
        d_frame = d_dark = d_flat = nullptr;
        d_raw = nullptr;
    }
};
