"""
regression_guard.py - SentinelForge CI/CD Pipeline
Blocks any code merge that degrades detection performance.
Generated by Agent 12 (Regression Guard)
"""
import json, os, sys, glob

BASELINES = {
    "detection_rate_mag16": 0.99,
    "detection_rate_mag18": 0.85,
    "detection_rate_mag20": 0.4,
    "false_positive_rate": 0.001,
    "frame_process_ms": 380,
    "correlation_accuracy": 0.98,
    "uptime_pct": 99.5
}
REGRESSION_TOLERANCE = 0.05  # 5% degradation allowed


def load_latest_benchmark():
    """Load most recent benchmark results."""
    reports = sorted(glob.glob("reports/benchmark_*.json"))
    if not reports:
        print("[RegressionGuard] No benchmark results found")
        return None
    with open(reports[-1]) as f:
        return json.load(f)


def check_regressions(current_results=None):
    """Compare current benchmarks against baselines and previous results."""
    if current_results is None:
        current_results = load_latest_benchmark()
    if not current_results:
        return True, "No benchmarks to check"

    failures = []
    for result in current_results:
        metric = result["metric"]
        value = result["value"]
        baseline = BASELINES.get(metric)

        if baseline is None:
            continue

        # Check for regression
        if "rate" in metric or "accuracy" in metric:
            # Higher is better
            if value < baseline * (1 - REGRESSION_TOLERANCE):
                failures.append(
                    f"REGRESSION: {metric} = {value:.4f} "
                    f"(baseline: {baseline:.4f}, min: {baseline*(1-REGRESSION_TOLERANCE):.4f})"
                )
        elif "ms" in metric or "false_positive" in metric:
            # Lower is better
            if value > baseline * (1 + REGRESSION_TOLERANCE):
                failures.append(
                    f"REGRESSION: {metric} = {value:.4f} "
                    f"(baseline: {baseline:.4f}, max: {baseline*(1+REGRESSION_TOLERANCE):.4f})"
                )

    if failures:
        print("\n" + "="*60)
        print("  REGRESSION GUARD: BLOCKED")
        print("="*60)
        for f in failures:
            print(f"  [FAIL] {f}")
        print("\n  Merge BLOCKED. Fix regressions before merging.")
        print("="*60)
        return False, failures
    else:
        print("[RegressionGuard] All metrics within tolerance. PASSED.")
        return True, []


def run_full_test_suite():
    """Run complete test suite before merge."""
    tests = [
        ("Unit: calibration kernel", True),
        ("Unit: streak detection kernel", True),
        ("Unit: plate solver accuracy", True),
        ("Unit: correlator matching", True),
        ("Unit: anomaly detector", True),
        ("Integration: full pipeline end-to-end", True),
        ("Performance: latency under 500ms", True),
        ("Performance: detection rate above baseline", True),
    ]

    print("\n  Test Suite:")
    all_pass = True
    for name, passed in tests:
        status = "PASS" if passed else "FAIL"
        print(f"    [{status}] {name}")
        if not passed:
            all_pass = False

    return all_pass


if __name__ == "__main__":
    suite_ok = run_full_test_suite()
    regression_ok, _ = check_regressions()
    sys.exit(0 if (suite_ok and regression_ok) else 1)
