"""
simulate_frames.py - SentinelForge Test Infrastructure
Generates synthetic telescope frames with injected streaks and stars.
Ground truth is saved alongside for detection accuracy measurement.
Generated by Agent 9 (Data Simulator)
"""
import numpy as np
import json
import os
from dataclasses import dataclass, asdict
from typing import List

FRAME_WIDTH  = 4096
FRAME_HEIGHT = 4096
BIT_DEPTH    = 16
MAX_ADU      = (1 << BIT_DEPTH) - 1


@dataclass
class GroundTruth:
    """Known injected source for validation."""
    x_center: float
    y_center: float
    magnitude: float
    source_type: str        # "star", "streak"
    streak_angle_deg: float = 0
    streak_length_px: float = 0
    snr_expected: float = 0


def generate_background(width: int, height: int,
                         sky_level: float = 100.0,
                         read_noise: float = 10.0) -> np.ndarray:
    """Generate realistic sky background with Poisson + Gaussian noise."""
    # Poisson sky photon noise
    sky = np.random.poisson(sky_level, (height, width)).astype(np.float32)
    # Gaussian read noise
    sky += np.random.normal(0, read_noise, (height, width))
    return np.clip(sky, 0, MAX_ADU).astype(np.uint16)


def inject_star(frame: np.ndarray, x: float, y: float,
                brightness: float, fwhm: float = 2.5) -> float:
    """Inject a Gaussian PSF star at (x, y). Returns actual SNR."""
    sigma = fwhm / 2.355
    r = int(4 * sigma) + 1
    total_flux = 0

    for dy in range(-r, r+1):
        for dx in range(-r, r+1):
            px, py = int(x + dx), int(y + dy)
            if 0 <= px < frame.shape[1] and 0 <= py < frame.shape[0]:
                dist2 = dx*dx + dy*dy
                val = brightness * np.exp(-dist2 / (2 * sigma**2))
                frame[py, px] = min(MAX_ADU, frame[py, px] + int(val))
                total_flux += val

    # Approximate SNR
    bg_noise = np.sqrt(100 + 10**2)  # sky + read noise
    n_pix = np.pi * (fwhm/2)**2
    snr = total_flux / (bg_noise * np.sqrt(n_pix))
    return snr


def inject_streak(frame: np.ndarray, x: float, y: float,
                  angle_deg: float, length_px: float,
                  brightness_per_px: float) -> float:
    """Inject a linear streak at given angle. Returns actual SNR."""
    angle_rad = np.radians(angle_deg)
    cos_a = np.cos(angle_rad)
    sin_a = np.sin(angle_rad)
    total_flux = 0
    n_pixels = 0

    for k in np.linspace(-length_px/2, length_px/2, int(length_px * 2)):
        px = int(x + k * cos_a)
        py = int(y + k * sin_a)
        if 0 <= px < frame.shape[1] and 0 <= py < frame.shape[0]:
            # Spread across 3 pixel width (PSF convolved streak)
            for offset in [-1, 0, 1]:
                ppx = px + int(offset * sin_a)
                ppy = py - int(offset * cos_a)
                if 0 <= ppx < frame.shape[1] and 0 <= ppy < frame.shape[0]:
                    weight = [0.25, 0.5, 0.25][offset + 1]
                    val = int(brightness_per_px * weight)
                    frame[ppy, ppx] = min(MAX_ADU, frame[ppy, ppx] + val)
                    total_flux += val
                    n_pixels += 1

    bg_noise = np.sqrt(100 + 10**2)
    snr = total_flux / (bg_noise * np.sqrt(max(n_pixels, 1)))
    return snr


def generate_test_frame(n_stars: int = 200, n_streaks: int = 5,
                         streak_mag_range: tuple = (14, 20),
                         output_dir: str = "test_data") -> dict:
    """Generate one synthetic frame with ground truth."""

    os.makedirs(output_dir, exist_ok=True)

    frame = generate_background(FRAME_WIDTH, FRAME_HEIGHT)
    ground_truth: List[GroundTruth] = []

    # Inject stars (stationary reference sources)
    for _ in range(n_stars):
        x = np.random.uniform(50, FRAME_WIDTH - 50)
        y = np.random.uniform(50, FRAME_HEIGHT - 50)
        mag = np.random.uniform(8, 16)
        brightness = 10**((16 - mag) / 2.5) * 100
        snr = inject_star(frame, x, y, brightness)

        ground_truth.append(GroundTruth(
            x_center=x, y_center=y, magnitude=mag,
            source_type="star", snr_expected=snr
        ))

    # Inject satellite/debris streaks
    for i in range(n_streaks):
        x = np.random.uniform(100, FRAME_WIDTH - 100)
        y = np.random.uniform(100, FRAME_HEIGHT - 100)
        angle = np.random.uniform(0, 180)
        length = np.random.uniform(10, 100)
        mag = np.random.uniform(*streak_mag_range)
        brightness = 10**((18 - mag) / 2.5) * 20

        snr = inject_streak(frame, x, y, angle, length, brightness)

        ground_truth.append(GroundTruth(
            x_center=x, y_center=y, magnitude=mag,
            source_type="streak", streak_angle_deg=angle,
            streak_length_px=length, snr_expected=snr
        ))

    # Save frame as raw binary
    frame_path = os.path.join(output_dir, "test_frame.raw")
    frame.tofile(frame_path)

    # Save ground truth
    gt_path = os.path.join(output_dir, "ground_truth.json")
    with open(gt_path, "w") as f:
        json.dump([asdict(g) for g in ground_truth], f, indent=2)

    return {
        "frame_path": frame_path,
        "truth_path": gt_path,
        "n_stars": n_stars,
        "n_streaks": n_streaks,
        "frame_size_mb": os.path.getsize(frame_path) / (1024*1024)
    }


if __name__ == "__main__":
    result = generate_test_frame()
    print(f"Generated: {result}")
