"""
source_extract.py - SentinelForge Edge Pipeline
Assembles detection tables from C++ pipeline outputs.
Applies plate solution (WCS) to convert pixel coords to sky coords.
Generated by Agent 5 (Pipeline Orchestrator)
"""
import json
import time
import struct
from dataclasses import dataclass, asdict
from typing import List, Optional
from pathlib import Path

SNR_THRESHOLD = 5.0
MIN_STREAK_LEN = 3


@dataclass
class Detection:
    """Single detected source/streak in a telescope frame."""
    ra_deg: float           # Right Ascension (J2000, degrees)
    dec_deg: float          # Declination (J2000, degrees)
    ra_err_arcsec: float    # RA uncertainty
    dec_err_arcsec: float   # Dec uncertainty
    magnitude: float        # Instrumental magnitude
    snr: float              # Signal-to-noise ratio
    streak_length_arcsec: float  # 0 for point sources
    streak_angle_deg: float
    angular_rate_arcsec_s: float  # 0 for stationary objects
    pixel_x: float
    pixel_y: float
    timestamp_utc: float    # Unix epoch, microsecond precision
    exposure_sec: float
    frame_id: int
    sensor_id: str
    detection_type: str     # "point", "streak", "extended"


@dataclass
class WCSSolution:
    """World Coordinate System plate solution."""
    crpix1: float   # Reference pixel X
    crpix2: float   # Reference pixel Y
    crval1: float   # Reference RA (deg)
    crval2: float   # Reference Dec (deg)
    cd1_1: float    # Transformation matrix
    cd1_2: float
    cd2_1: float
    cd2_2: float
    residual_arcsec: float  # Plate solve fit quality

    def pixel_to_sky(self, x: float, y: float) -> tuple:
        dx = x - self.crpix1
        dy = y - self.crpix2
        ra = self.crval1 + self.cd1_1 * dx + self.cd1_2 * dy
        dec = self.crval2 + self.cd2_1 * dx + self.cd2_2 * dy
        return ra, dec


class SourceExtractor:
    """Assembles detection table from pipeline outputs."""

    def __init__(self, sensor_id: str):
        self.sensor_id = sensor_id
        self.detections: List[Detection] = []

    def process_frame(self, streak_data: list, point_data: list,
                      wcs: WCSSolution, frame_id: int,
                      timestamp: float, exposure: float) -> List[Detection]:
        """
        Merge streak detections and point source detections,
        apply WCS transform, and build detection table.
        """
        self.detections = []

        # Process streaks from GPU kernel output
        for s in streak_data:
            if s.get("snr", 0) < SNR_THRESHOLD:
                continue
            if s.get("length_px", 0) < MIN_STREAK_LEN:
                continue

            cx = (s["x_start"] + s["x_end"]) / 2
            cy = (s["y_start"] + s["y_end"]) / 2
            ra, dec = wcs.pixel_to_sky(cx, cy)

            # Compute angular rate from streak length and exposure
            plate_scale = abs(wcs.cd1_1) * 3600  # arcsec/pixel
            streak_arcsec = s["length_px"] * plate_scale
            angular_rate = streak_arcsec / exposure if exposure > 0 else 0

            det = Detection(
                ra_deg=ra, dec_deg=dec,
                ra_err_arcsec=wcs.residual_arcsec,
                dec_err_arcsec=wcs.residual_arcsec,
                magnitude=s.get("magnitude", -2.5 * __import__("math").log10(max(s.get("brightness", 1), 1))),
                snr=s["snr"],
                streak_length_arcsec=streak_arcsec,
                streak_angle_deg=s.get("angle_deg", 0),
                angular_rate_arcsec_s=angular_rate,
                pixel_x=cx, pixel_y=cy,
                timestamp_utc=timestamp,
                exposure_sec=exposure,
                frame_id=frame_id,
                sensor_id=self.sensor_id,
                detection_type="streak"
            )
            self.detections.append(det)

        # Process point sources (stationary)
        for p in point_data:
            if p.get("snr", 0) < SNR_THRESHOLD:
                continue

            ra, dec = wcs.pixel_to_sky(p["x"], p["y"])
            det = Detection(
                ra_deg=ra, dec_deg=dec,
                ra_err_arcsec=wcs.residual_arcsec * 0.5,
                dec_err_arcsec=wcs.residual_arcsec * 0.5,
                magnitude=p.get("magnitude", 0),
                snr=p["snr"],
                streak_length_arcsec=0,
                streak_angle_deg=0,
                angular_rate_arcsec_s=0,
                pixel_x=p["x"], pixel_y=p["y"],
                timestamp_utc=timestamp,
                exposure_sec=exposure,
                frame_id=frame_id,
                sensor_id=self.sensor_id,
                detection_type="point"
            )
            self.detections.append(det)

        return self.detections

    def to_json(self) -> str:
        return json.dumps([asdict(d) for d in self.detections], indent=2)

    def to_upload_package(self) -> dict:
        """Minimal package for cloud upload (~10KB per frame)."""
        return {
            "sensor_id": self.sensor_id,
            "n_detections": len(self.detections),
            "detections": [asdict(d) for d in self.detections],
            "generated_at": time.time()
        }
