/**
 * streak_detect.cu — SentinelForge Edge Pipeline
 * GPU-accelerated satellite/debris streak detection.
 * Matched filter bank at 180 angles x 5 lengths + peak finder.
 * Generated by Agent 2 (GPU Kernel Engineer)
 */

#include <cuda_runtime.h>
#include <cstdio>
#include <cmath>

constexpr int   N_ANGLES        = 180;
constexpr float SNR_THRESHOLD   = 5.0f;
constexpr int   MIN_STREAK_LEN  = 3;
constexpr int   MAX_DETECTIONS  = 2048;
constexpr int   BLOCK_DIM       = 16;

// ─── Detection Structure ───────────────────────────────────────

struct Detection {
    float x_start, y_start;    // Streak start pixel
    float x_end, y_end;        // Streak end pixel
    float brightness;          // Integrated flux
    float snr;                 // Signal-to-noise ratio
    float angle_deg;           // Motion direction
    float length_px;           // Streak length in pixels
    float angular_rate;        // arcsec/sec (filled by host)
};

// ─── Noise Estimation Kernel ───────────────────────────────────

/**
 * Estimate local noise level in 32x32 windows.
 * Uses MAD (Median Absolute Deviation) — robust to sources.
 */
__global__ void estimate_noise_kernel(
    const float* __restrict__ frame,
    float* __restrict__ noise_map,
    int width, int height
) {
    int bx = blockIdx.x;   // Tile index
    int by = blockIdx.y;
    int tid = threadIdx.x;
    
    constexpr int NOISE_TILE = 32;
    constexpr int NOISE_PIXELS = NOISE_TILE * NOISE_TILE;
    
    int tiles_x = width / NOISE_TILE;
    if (bx >= tiles_x || by >= (height / NOISE_TILE)) return;
    
    __shared__ float tile[NOISE_PIXELS];
    
    // Load tile
    int px = bx * NOISE_TILE + (tid % NOISE_TILE);
    int py = by * NOISE_TILE + (tid / NOISE_TILE);
    if (tid < NOISE_PIXELS && px < width && py < height)
        tile[tid] = frame[py * width + px];
    else if (tid < NOISE_PIXELS)
        tile[tid] = 0.0f;
    __syncthreads();
    
    // Thread 0 computes MAD
    if (tid == 0) {
        // Simple median estimate (use middle element of sorted subset)
        // For speed, use approximate: median of 64 samples
        float samples[64];
        for (int i = 0; i < 64; i++)
            samples[i] = tile[i * (NOISE_PIXELS / 64)];
        
        // Bubble sort 64 elements
        for (int i = 0; i < 63; i++)
            for (int j = i+1; j < 64; j++)
                if (samples[i] > samples[j]) {
                    float tmp = samples[i];
                    samples[i] = samples[j];
                    samples[j] = tmp;
                }
        
        float med = samples[32];
        
        // MAD
        for (int i = 0; i < 64; i++)
            samples[i] = fabsf(tile[i * (NOISE_PIXELS / 64)] - med);
        for (int i = 0; i < 63; i++)
            for (int j = i+1; j < 64; j++)
                if (samples[i] > samples[j]) {
                    float tmp = samples[i];
                    samples[i] = samples[j];
                    samples[j] = tmp;
                }
        
        float sigma = 1.4826f * samples[32];
        noise_map[by * tiles_x + bx] = fmaxf(sigma, 1.0f);  // Floor at 1.0
    }
}

// ─── Matched Filter Kernel ─────────────────────────────────────

/**
 * Apply matched filter at a single angle and length.
 * Each thread handles one pixel — sums along the line direction.
 * Output: response map (higher = more streak-like).
 */
__global__ void matched_filter_kernel(
    const float* __restrict__ frame,
    float* __restrict__ response,
    int width, int height,
    float cos_angle, float sin_angle,
    int kernel_length
) {
    int x = blockIdx.x * blockDim.x + threadIdx.x;
    int y = blockIdx.y * blockDim.y + threadIdx.y;
    if (x >= width || y >= height) return;
    
    float sum = 0.0f;
    int count = 0;
    int half = kernel_length / 2;
    
    for (int k = -half; k <= half; k++) {
        int sx = x + __float2int_rn(k * cos_angle);
        int sy = y + __float2int_rn(k * sin_angle);
        
        if (sx >= 0 && sx < width && sy >= 0 && sy < height) {
            sum += frame[sy * width + sx];
            count++;
        }
    }
    
    response[y * width + x] = (count > 0) ? sum / sqrtf((float)count) : 0.0f;
}

// ─── Peak Detection Kernel ─────────────────────────────────────

/**
 * Find local maxima in response map that exceed SNR threshold.
 * Uses 5x5 non-maximum suppression window.
 * Atomically appends to global detection list.
 */
__global__ void peak_detect_kernel(
    const float* __restrict__ response,
    const float* __restrict__ noise_map,
    Detection* __restrict__ detections,
    int* __restrict__ detection_count,
    int width, int height,
    int noise_tiles_x,
    float angle_deg,
    float kernel_length,
    float snr_threshold
) {
    int x = blockIdx.x * blockDim.x + threadIdx.x;
    int y = blockIdx.y * blockDim.y + threadIdx.y;
    if (x < 3 || x >= width - 3 || y < 3 || y >= height - 3) return;
    
    float val = response[y * width + x];
    
    // Get local noise
    int tx = x / 32;
    int ty = y / 32;
    float noise = noise_map[ty * noise_tiles_x + tx];
    float snr = val / noise;
    
    if (snr < snr_threshold) return;
    
    // Non-maximum suppression: is this pixel the local max in 5x5?
    bool is_max = true;
    for (int dy = -2; dy <= 2 && is_max; dy++)
        for (int dx = -2; dx <= 2 && is_max; dx++)
            if (dx != 0 || dy != 0)
                if (response[(y+dy) * width + (x+dx)] >= val)
                    is_max = false;
    
    if (!is_max) return;
    
    // Atomic append to detection list
    int idx = atomicAdd(detection_count, 1);
    if (idx < MAX_DETECTIONS) {
        Detection det;
        float half_len = kernel_length / 2.0f;
        float cos_a = cosf(angle_deg * 3.14159265f / 180.0f);
        float sin_a = sinf(angle_deg * 3.14159265f / 180.0f);
        
        det.x_start = x - half_len * cos_a;
        det.y_start = y - half_len * sin_a;
        det.x_end   = x + half_len * cos_a;
        det.y_end   = y + half_len * sin_a;
        det.brightness = val * sqrtf(kernel_length);
        det.snr = snr;
        det.angle_deg = angle_deg;
        det.length_px = kernel_length;
        det.angular_rate = 0.0f;  // Filled by host with plate solution
        
        detections[idx] = det;
    }
}

// ─── Host Interface ────────────────────────────────────────────

struct StreakDetector {
    float* d_response;
    float* d_noise_map;
    Detection* d_detections;
    int* d_detection_count;
    int width, height;
    
    bool allocate(int w, int h) {
        width = w;
        height = h;
        cudaMalloc(&d_response, w * h * sizeof(float));
        cudaMalloc(&d_noise_map, (w/32) * (h/32) * sizeof(float));
        cudaMalloc(&d_detections, MAX_DETECTIONS * sizeof(Detection));
        cudaMalloc(&d_detection_count, sizeof(int));
        return true;
    }
    
    /**
     * DetectStreaks: Full detection pipeline.
     * Runs matched filter bank at 180 angles x multiple lengths,
     * then extracts peaks above SNR threshold.
     */
    int detect(const float* d_frame, Detection* h_detections, cudaStream_t stream = 0) {
        // Reset detection count
        cudaMemsetAsync(d_detection_count, 0, sizeof(int), stream);
        
        dim3 block(BLOCK_DIM, BLOCK_DIM);
        dim3 grid((width + BLOCK_DIM - 1) / BLOCK_DIM,
                  (height + BLOCK_DIM - 1) / BLOCK_DIM);
        
        // Step 1: Estimate noise
        int noise_tx = width / 32;
        int noise_ty = height / 32;
        dim3 noise_grid(noise_tx, noise_ty);
        estimate_noise_kernel<<<noise_grid, 1024, 0, stream>>>(
            d_frame, d_noise_map, width, height
        );
        
        // Step 2: Run matched filter bank
        int kernel_lengths[] = {5, 10, 20, 50, 100};
        int n_lengths = 5;
        
        for (int ai = 0; ai < N_ANGLES; ai++) {
            float angle = (float)ai * 180.0f / N_ANGLES;
            float cos_a = cosf(angle * 3.14159265f / 180.0f);
            float sin_a = sinf(angle * 3.14159265f / 180.0f);
            
            for (int li = 0; li < n_lengths; li++) {
                // Apply matched filter
                matched_filter_kernel<<<grid, block, 0, stream>>>(
                    d_frame, d_response, width, height,
                    cos_a, sin_a, kernel_lengths[li]
                );
                
                // Extract peaks
                peak_detect_kernel<<<grid, block, 0, stream>>>(
                    d_response, d_noise_map, d_detections, d_detection_count,
                    width, height, noise_tx, angle, (float)kernel_lengths[li],
                    SNR_THRESHOLD
                );
            }
        }
        
        // Copy results back
        int h_count = 0;
        cudaMemcpyAsync(&h_count, d_detection_count, sizeof(int),
                        cudaMemcpyDeviceToHost, stream);
        cudaStreamSynchronize(stream);
        
        h_count = min(h_count, MAX_DETECTIONS);
        if (h_count > 0) {
            cudaMemcpy(h_detections, d_detections,
                      h_count * sizeof(Detection), cudaMemcpyDeviceToHost);
        }
        
        return h_count;
    }
    
    void release() {
        cudaFree(d_response);
        cudaFree(d_noise_map);
        cudaFree(d_detections);
        cudaFree(d_detection_count);
    }
};
