"""
train_model.py - SentinelForge ML Pipeline
PyTorch streak detection model: trains on synthetic data, exports ONNX.
Generated by Agent 6 (ML Trainer)
"""
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import numpy as np
import json, os, time

class StreakDetectionNet(nn.Module):
    """Lightweight CNN for streak vs noise classification."""
    def __init__(self):
        super().__init__()
        self.features = nn.Sequential(
            nn.Conv2d(1, 32, 3, padding=1), nn.BatchNorm2d(32), nn.ReLU(),
            nn.MaxPool2d(2),
            nn.Conv2d(32, 64, 3, padding=1), nn.BatchNorm2d(64), nn.ReLU(),
            nn.MaxPool2d(2),
            nn.Conv2d(64, 128, 3, padding=1), nn.BatchNorm2d(128), nn.ReLU(),
            nn.AdaptiveAvgPool2d(4),
        )
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(128 * 4 * 4, 256), nn.ReLU(), nn.Dropout(0.3),
            nn.Linear(256, 64), nn.ReLU(),
            nn.Linear(64, 3)  # classes: noise, point_source, streak
        )

    def forward(self, x):
        return self.classifier(self.features(x))


class StreakDataset(Dataset):
    """Realistic synthetic dataset of 64x64 cutouts: noise, stars, streaks.

    Generates patches with:
    - Poisson shot noise + Gaussian read noise (realistic CCD model)
    - Random background gradient (sky glow variation across field)
    - Gaussian PSF convolution for stars (FWHM 2-4 px)
    - Randomized streak position, angle, length, and brightness
    - Random hot pixels (detector defects)
    - Random label assignment (no data leakage from index ordering)
    """
    def __init__(self, n_samples=10000, seed=None):
        self.n = n_samples
        self.data = []
        self.labels = []
        rng = np.random.RandomState(seed)

        for _ in range(n_samples):
            label = rng.randint(0, 3)  # Random label — no i%3 leakage

            # Background: sky + gradient + Poisson shot noise
            sky_level = rng.uniform(80, 150)
            grad_x = rng.uniform(-0.5, 0.5)
            grad_y = rng.uniform(-0.5, 0.5)
            xx, yy = np.meshgrid(np.arange(64), np.arange(64))
            background = sky_level + grad_x * (xx - 32) + grad_y * (yy - 32)
            patch = rng.poisson(np.clip(background, 1, None)).astype(np.float32)

            # Read noise (Gaussian, ~5-15 ADU RMS)
            read_noise = rng.normal(0, rng.uniform(5, 15), (64, 64))
            patch += read_noise.astype(np.float32)

            # Random hot pixels (1-5 per patch)
            n_hot = rng.randint(1, 6)
            for _ in range(n_hot):
                hx, hy = rng.randint(0, 64, 2)
                patch[hy, hx] += rng.uniform(200, 1000)

            if label == 1:  # Point source (star) with Gaussian PSF
                cx = rng.randint(10, 54)
                cy = rng.randint(10, 54)
                fwhm = rng.uniform(2.0, 4.0)
                sigma = fwhm / 2.355
                flux = rng.uniform(300, 2000)
                for dy in range(-6, 7):
                    for dx in range(-6, 7):
                        ny, nx = cy + dy, cx + dx
                        if 0 <= ny < 64 and 0 <= nx < 64:
                            r2 = dx**2 + dy**2
                            patch[ny, nx] += flux * np.exp(-r2 / (2 * sigma**2))

            elif label == 2:  # Streak (satellite trail)
                cx = rng.randint(10, 54)
                cy = rng.randint(10, 54)
                angle = rng.uniform(0, np.pi)
                length = rng.randint(12, 50)
                brightness = rng.uniform(100, 500)
                width = rng.uniform(1.0, 2.5)  # PSF-broadened streak
                cos_a, sin_a = np.cos(angle), np.sin(angle)
                for k in range(-length // 2, length // 2):
                    for w in np.linspace(-width, width, 5):
                        px = int(cx + k * cos_a + w * sin_a)
                        py = int(cy + k * sin_a - w * cos_a)
                        if 0 <= px < 64 and 0 <= py < 64:
                            patch[py, px] += brightness * np.exp(-w**2 / (2 * (width/2)**2))

            # Normalize (zero-mean, unit-variance)
            patch = (patch - patch.mean()) / (patch.std() + 1e-6)
            self.data.append(patch)
            self.labels.append(label)

    def __len__(self): return self.n
    def __getitem__(self, idx):
        x = torch.tensor(self.data[idx]).unsqueeze(0)
        y = torch.tensor(self.labels[idx])
        return x, y


def train(epochs=20, batch_size=64, lr=1e-3, output_dir="models"):
    os.makedirs(output_dir, exist_ok=True)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"[MLTrainer] Device: {device}")

    model = StreakDetectionNet().to(device)
    dataset = StreakDataset(n_samples=9000)
    val_dataset = StreakDataset(n_samples=1000)
    loader = DataLoader(dataset, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=batch_size)

    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=lr)
    scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=10, gamma=0.5)

    best_acc = 0
    for epoch in range(epochs):
        model.train()
        total_loss = 0
        for x, y in loader:
            x, y = x.to(device), y.to(device)
            optimizer.zero_grad()
            out = model(x)
            loss = criterion(out, y)
            loss.backward()
            optimizer.step()
            total_loss += loss.item()
        scheduler.step()

        # Validate
        model.eval()
        correct, total = 0, 0
        with torch.no_grad():
            for x, y in val_loader:
                x, y = x.to(device), y.to(device)
                pred = model(x).argmax(1)
                correct += (pred == y).sum().item()
                total += y.size(0)
        acc = correct / total
        print(f"  Epoch {epoch+1}/{epochs}: loss={total_loss/len(loader):.4f} val_acc={acc:.4f}")

        if acc > best_acc:
            best_acc = acc
            torch.save(model.state_dict(), f"{output_dir}/streak_det_best.pth")

    # Export ONNX
    model.eval()
    dummy = torch.randn(1, 1, 64, 64).to(device)
    onnx_path = f"{output_dir}/streak_det.onnx"
    torch.onnx.export(model, dummy, onnx_path, input_names=["image"],
                      output_names=["classification"], opset_version=17)
    print(f"[MLTrainer] Exported ONNX: {onnx_path}")
    print(f"[MLTrainer] Best val accuracy: {best_acc:.4f}")
    return {"best_accuracy": best_acc, "onnx_path": onnx_path}

if __name__ == "__main__":
    train()
